/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => VerseMarkersPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian5 = require("obsidian");

// src/detection.ts
var VERSE_MARKER_REGEX = /\[\d+[a-z]*\](?=\s|$)/gm;
function getVerseRegex() {
  return new RegExp(VERSE_MARKER_REGEX.source, VERSE_MARKER_REGEX.flags);
}
function atVerseBoundary(text, index) {
  if (index <= 0)
    return true;
  const prev = text.charAt(index - 1);
  return prev === ">" || /\s/.test(prev);
}
function execVerseMarker(re, text) {
  let m;
  while ((m = re.exec(text)) !== null) {
    if (atVerseBoundary(text, m.index))
      return m;
  }
  return null;
}
function hasVerseMarker(text) {
  return execVerseMarker(getVerseRegex(), text) !== null;
}
function parseMarkerToken(token) {
  const m = /^\[(\d+)([a-z]*)\]$/.exec(token);
  if (!m)
    return { number: NaN, part: null };
  return { number: parseInt(m[1], 10), part: m[2] === "" ? null : m[2] };
}
function partToIndex(part) {
  return part.charCodeAt(0) - "a".charCodeAt(0);
}
function scanMarkers(text) {
  const re = getVerseRegex();
  const hits = [];
  let m;
  while ((m = execVerseMarker(re, text)) !== null) {
    const { number, part } = parseMarkerToken(m[0]);
    hits.push({
      number,
      part,
      index: m.index,
      afterMarker: m.index + m[0].length
    });
  }
  return hits;
}
var HEADING_LINE_REGEX = /^\s*#{1,6}\s+\S.*$/;
function stripBlockquoteMarker(line) {
  return line.replace(/^\s*>\s?/, "");
}
function splitSegmentByFootnotes(segment) {
  const re = new RegExp(FOOTNOTE_REF_REGEX.source, "g");
  const parts = [];
  let lastIndex = 0;
  let m;
  while ((m = re.exec(segment)) !== null) {
    const cut = m.index + m[0].length;
    if (/\S/.test(segment.slice(lastIndex, m.index)) && /\S/.test(segment.slice(cut))) {
      parts.push(segment.slice(lastIndex, cut));
      lastIndex = cut;
    }
  }
  parts.push(segment.slice(lastIndex));
  return parts;
}
function versePartSegments(rawContent) {
  const lines = rawContent.split("\n").map(stripBlockquoteMarker);
  const segments = [[]];
  for (const line of lines) {
    if (HEADING_LINE_REGEX.test(line)) {
      segments.push([]);
    } else {
      segments[segments.length - 1].push(line);
    }
  }
  return segments.map(
    (group) => splitSegmentByFootnotes(group.join("\n")).map((part) => part.trim())
  );
}
function splitVerseParts(rawContent) {
  return versePartSegments(rawContent).flat();
}
function findVerseSpan(text, verseNumber) {
  const re = getVerseRegex();
  let spanStart = -1;
  let spanEnd = text.length;
  let match;
  while ((match = execVerseMarker(re, text)) !== null) {
    const num = parseMarkerToken(match[0]).number;
    const afterMarker = match.index + match[0].length;
    if (spanStart === -1 && num === verseNumber) {
      if (text[afterMarker] !== " ")
        return null;
      spanStart = afterMarker + 1;
    } else if (spanStart !== -1) {
      spanEnd = match.index;
      break;
    }
  }
  if (spanStart === -1)
    return null;
  return { start: spanStart, end: spanEnd };
}
function getVerseParts(text, verseNumber) {
  const span = findVerseSpan(text, verseNumber);
  if (!span)
    return null;
  return splitVerseParts(text.slice(span.start, span.end));
}
function getVerseFragments(text, verseNumber) {
  const hits = scanMarkers(text);
  const fragments = [];
  for (let i = 0; i < hits.length; i++) {
    if (hits[i].number !== verseNumber)
      continue;
    if (text[hits[i].afterMarker] !== " ")
      continue;
    const contentStart = hits[i].afterMarker + 1;
    const contentEnd = i + 1 < hits.length ? hits[i + 1].index : text.length;
    const raw = text.slice(contentStart, contentEnd);
    const content = splitVerseParts(raw).filter((p) => p.length > 0).join(" ");
    fragments.push({ part: hits[i].part, content });
  }
  return fragments;
}
function getVerseContent(text, verseNumber, part = null) {
  const fragments = getVerseFragments(text, verseNumber);
  if (fragments.length === 0)
    return null;
  if (part !== null) {
    const explicit = fragments.find((f) => f.part === part);
    if (explicit)
      return explicit.content;
    if (fragments.length === 1 && fragments[0].part === null) {
      const span = findVerseSpan(text, verseNumber);
      if (!span)
        return null;
      const parts = splitVerseParts(text.slice(span.start, span.end));
      const idx = partToIndex(part);
      if (idx < 0 || idx >= parts.length)
        return null;
      return parts[idx];
    }
    return null;
  }
  return fragments.map((f) => f.content).filter((c) => c.length > 0).join(" ");
}
function verseBlockquotePrefix(text, verseNumber) {
  const re = getVerseRegex();
  let match;
  while ((match = execVerseMarker(re, text)) !== null) {
    if (parseMarkerToken(match[0]).number !== verseNumber)
      continue;
    const lineStart = text.lastIndexOf("\n", match.index - 1) + 1;
    const prefix = /^(\s*(?:>\s?)+)/.exec(text.slice(lineStart, match.index));
    return prefix ? prefix[1] : "";
  }
  return "";
}
function getVerseRangeRawText(text, start, end) {
  const hits = scanMarkers(text);
  let firstIdx = -1;
  let lastIdx = -1;
  for (let i = 0; i < hits.length; i++) {
    if (hits[i].number >= start && hits[i].number <= end) {
      if (firstIdx === -1)
        firstIdx = i;
      lastIdx = i;
    }
  }
  if (firstIdx === -1)
    return null;
  const startPos = lineLeadStart(text, hits[firstIdx].index);
  const contentEnd = lastIdx + 1 < hits.length ? lineLeadStart(text, hits[lastIdx + 1].index) : text.length;
  const raw = text.slice(startPos, contentEnd).trimEnd();
  return stripTrailingHeadingsBeforeNextVerse(raw);
}
function lineLeadStart(text, markerIndex) {
  const lineStart = text.lastIndexOf("\n", markerIndex - 1) + 1;
  const lead = text.slice(lineStart, markerIndex);
  return /^\s*(?:>\s?)*$/.test(lead) ? lineStart : markerIndex;
}
function stripTrailingHeadingsBeforeNextVerse(raw) {
  const lines = raw.split("\n");
  let end = lines.length;
  while (end > 0) {
    let i = end - 1;
    while (i >= 0 && /^\s*$/.test(stripBlockquoteMarker(lines[i])))
      i--;
    if (i < 0) {
      end = 0;
      break;
    }
    if (HEADING_LINE_REGEX.test(stripBlockquoteMarker(lines[i]))) {
      end = i;
      continue;
    }
    break;
  }
  return lines.slice(0, end).join("\n").trimEnd();
}
var FOOTNOTE_REF_REGEX = /\[\^([^\]\s]+)\](?!:)/g;
var FOOTNOTE_DEF_HEAD_REGEX = /^\[\^([^\]\s]+)\]:/;
function appendMissingFootnoteDefinitions(slice, fullText) {
  const referenced = /* @__PURE__ */ new Set();
  let m;
  const refRe = new RegExp(FOOTNOTE_REF_REGEX.source, FOOTNOTE_REF_REGEX.flags);
  while ((m = refRe.exec(slice)) !== null) {
    referenced.add(m[1]);
  }
  if (referenced.size === 0)
    return slice;
  const sliceLines = slice.split("\n");
  for (const line of sliceLines) {
    const head = FOOTNOTE_DEF_HEAD_REGEX.exec(line);
    if (head)
      referenced.delete(head[1]);
  }
  if (referenced.size === 0)
    return slice;
  const fullLines = fullText.split("\n");
  const appended = [];
  for (let i = 0; i < fullLines.length; i++) {
    const head = FOOTNOTE_DEF_HEAD_REGEX.exec(fullLines[i]);
    if (!head)
      continue;
    if (!referenced.has(head[1]))
      continue;
    const block = [fullLines[i]];
    let j = i + 1;
    while (j < fullLines.length) {
      const next = fullLines[j];
      if (next === "" || /^[ \t]/.test(next)) {
        block.push(next);
        j++;
      } else {
        break;
      }
    }
    while (block.length > 0 && block[block.length - 1] === "")
      block.pop();
    appended.push(block.join("\n"));
    referenced.delete(head[1]);
    if (referenced.size === 0)
      break;
  }
  if (appended.length === 0)
    return slice;
  return `${slice}

${appended.join("\n\n")}`;
}
function findVerseLine(text, verseNumber) {
  const re = getVerseRegex();
  let match;
  while ((match = execVerseMarker(re, text)) !== null) {
    const num = parseMarkerToken(match[0]).number;
    if (num === verseNumber) {
      let line = 0;
      for (let i = 0; i < match.index; i++) {
        if (text.charCodeAt(i) === 10)
          line++;
      }
      return line;
    }
  }
  return null;
}
function continuationPartAnchor(text, blockStartLine) {
  const lines = text.split("\n");
  let headingCount = 0;
  let verseNumber = null;
  for (let i = blockStartLine - 1; i >= 0; i--) {
    if (HEADING_LINE_REGEX.test(stripBlockquoteMarker(lines[i]))) {
      headingCount++;
      continue;
    }
    const marker = execVerseMarker(getVerseRegex(), lines[i]);
    if (marker) {
      verseNumber = parseMarkerToken(marker[0]).number;
      break;
    }
  }
  if (verseNumber === null || headingCount === 0)
    return null;
  let index = headingCount;
  const span = findVerseSpan(text, verseNumber);
  if (span) {
    const segments = versePartSegments(text.slice(span.start, span.end));
    for (let s = 0; s < headingCount && s < segments.length; s++) {
      index += segments[s].length - 1;
    }
  }
  return `verse-${verseNumber}${String.fromCharCode(97 + index)}`;
}
function partHasAnchor(text, verseNumber, part) {
  if (part === null)
    return true;
  if (scanMarkers(text).some((h) => h.number === verseNumber && h.part === part)) {
    return true;
  }
  const span = findVerseSpan(text, verseNumber);
  if (!span)
    return false;
  const segments = versePartSegments(text.slice(span.start, span.end));
  const target = partToIndex(part);
  let segmentStart = 0;
  for (const segment of segments) {
    if (segmentStart === target)
      return true;
    segmentStart += segment.length;
  }
  return false;
}
function firstFragmentPart(text, verseNumber) {
  const first = scanMarkers(text).find((h) => h.number === verseNumber);
  return first ? first.part : null;
}
var SEGMENT_SOURCE = String.raw`\d+[a-z]*(?::\d+[a-z]*)?`;
function parseVerseSegments(fragment, allowShorthand = false) {
  let core;
  if (fragment.startsWith("verse-")) {
    core = fragment.slice("verse-".length);
  } else if (allowShorthand) {
    core = fragment;
  } else {
    return null;
  }
  if (core.length === 0)
    return null;
  const segRe = new RegExp(`^(\\d+)([a-z]*)(?::(\\d+)([a-z]*))?$`);
  const segments = [];
  for (const piece of core.split("/")) {
    const m = segRe.exec(piece);
    if (!m)
      return null;
    const start = parseInt(m[1], 10);
    const startPart = m[2] === "" ? null : m[2];
    if (m[3] !== void 0) {
      segments.push({
        start,
        startPart,
        end: parseInt(m[3], 10),
        endPart: m[4] === "" ? null : m[4]
      });
    } else {
      segments.push({ start, startPart, end: start, endPart: startPart });
    }
  }
  return segments;
}
var VERSE_FRAGMENT_TEST_STRICT = new RegExp(
  `^verse-${SEGMENT_SOURCE}(?:/${SEGMENT_SOURCE})*$`
);
var VERSE_FRAGMENT_TEST_LOOSE = new RegExp(
  `^(?:verse-)?${SEGMENT_SOURCE}(?:/${SEGMENT_SOURCE})*$`
);

// src/postprocessor.ts
var SKIP_TAGS = /* @__PURE__ */ new Set([
  "A",
  "CODE",
  "PRE",
  "MATH",
  "MJX-CONTAINER",
  "TABLE",
  "IMG"
]);
var SKIP_CLASSES = [".math"];
var EMBED_SKIP_CLASSES = [".internal-embed", ".external-embed"];
function isInsideSkipped(node, skipEmbeds = true) {
  let current = node.parentNode;
  while (current !== null) {
    if (current.nodeType === Node.ELEMENT_NODE) {
      const el = current;
      if (SKIP_TAGS.has(el.tagName))
        return true;
      for (const cls of SKIP_CLASSES) {
        if (el.matches(cls))
          return true;
      }
      if (skipEmbeds) {
        for (const cls of EMBED_SKIP_CLASSES) {
          if (el.matches(cls))
            return true;
        }
      }
    }
    current = current.parentNode;
  }
  return false;
}
function processTextNode(textNode) {
  var _a;
  const text = (_a = textNode.nodeValue) != null ? _a : "";
  const re = getVerseRegex();
  const matches = [];
  let match;
  while ((match = execVerseMarker(re, text)) !== null) {
    matches.push(match);
  }
  if (matches.length === 0)
    return false;
  const parent = textNode.parentNode;
  if (!parent)
    return false;
  const fragment = activeDocument.createDocumentFragment();
  let lastIndex = 0;
  for (const m of matches) {
    const start = m.index;
    const token = m[0];
    const end = start + token.length;
    if (start > lastIndex) {
      fragment.appendChild(activeDocument.createTextNode(text.slice(lastIndex, start)));
    }
    const { number, part } = parseMarkerToken(token);
    const label = `${number}${part != null ? part : ""}`;
    const markerEl = activeDocument.createElement("span");
    markerEl.className = "verse-marker";
    markerEl.id = `verse-${label}`;
    markerEl.textContent = label;
    fragment.appendChild(markerEl);
    lastIndex = end;
  }
  if (lastIndex < text.length) {
    fragment.appendChild(activeDocument.createTextNode(text.slice(lastIndex)));
  }
  parent.replaceChild(fragment, textNode);
  return true;
}
function collectTextNodes(el, skipEmbeds = true) {
  const result = [];
  const walker = activeDocument.createTreeWalker(el, NodeFilter.SHOW_TEXT);
  let node;
  while ((node = walker.nextNode()) !== null) {
    const textNode = node;
    if (!isInsideSkipped(textNode, skipEmbeds)) {
      result.push(textNode);
    }
  }
  return result;
}
function styleVerseMarkers(el) {
  const textNodes = collectTextNodes(el, false);
  for (const tn of textNodes) {
    processTextNode(tn);
  }
}
function collectVerseAnchors(el, allowShorthand = false) {
  var _a, _b;
  const test = allowShorthand ? VERSE_FRAGMENT_TEST_LOOSE : VERSE_FRAGMENT_TEST_STRICT;
  const result = [];
  const anchors = el.getElementsByTagName("a");
  for (let i = 0; i < anchors.length; i++) {
    const a = anchors[i];
    const href = (_b = (_a = a.getAttribute("data-href")) != null ? _a : a.getAttribute("href")) != null ? _b : "";
    const hashIdx = href.indexOf("#");
    if (hashIdx === -1)
      continue;
    const fragment = href.slice(hashIdx + 1);
    if (test.test(fragment)) {
      result.push(a);
    }
  }
  return result;
}
function partAnchorForBlock(el, ctx) {
  const info = ctx.getSectionInfo(el);
  if (!info)
    return null;
  const sourceLines = info.text.split("\n");
  const blockText = sourceLines.slice(info.lineStart, info.lineEnd + 1).join("\n");
  if (hasVerseMarker(blockText))
    return null;
  return continuationPartAnchor(info.text, info.lineStart);
}
function injectPartAnchor(el, id) {
  if (el.querySelector(`#${CSS.escape(id)}`))
    return;
  const anchor = activeDocument.createElement("span");
  anchor.id = id;
  anchor.className = "verse-part-anchor";
  anchor.setAttribute("aria-hidden", "true");
  el.insertBefore(anchor, el.firstChild);
}
function versePostProcessor(el, ctx) {
  const textNodes = collectTextNodes(el);
  for (const tn of textNodes) {
    processTextNode(tn);
  }
  if (ctx) {
    const partId = partAnchorForBlock(el, ctx);
    if (partId)
      injectPartAnchor(el, partId);
  }
}

// src/commands.ts
var import_obsidian = require("obsidian");
function markerLabel(token) {
  const { number, part } = parseMarkerToken(token);
  return `${number}${part != null ? part : ""}`;
}
function nearestVerseAtOffset(text, cursorOffset) {
  const re = getVerseRegex();
  let match;
  let best = null;
  let bestDist = Infinity;
  while ((match = execVerseMarker(re, text)) !== null) {
    const start = match.index;
    const end = start + match[0].length;
    const dist = Math.min(Math.abs(cursorOffset - start), Math.abs(cursorOffset - end));
    if (dist < bestDist) {
      bestDist = dist;
      best = markerLabel(match[0]);
    }
  }
  return best;
}
function verseRangeInSelection(text, selFrom, selTo) {
  const slice = text.slice(selFrom, selTo);
  const re = getVerseRegex();
  const found = [];
  let match;
  while ((match = execVerseMarker(re, slice)) !== null) {
    found.push(markerLabel(match[0]));
  }
  if (found.length < 2)
    return null;
  return { first: found[0], last: found[found.length - 1] };
}
function registerCommands(plugin) {
  plugin.addCommand({
    id: "copy-verse-reference",
    name: "Copy verse reference",
    editorCallback(editor) {
      var _a, _b;
      const cursor = editor.getCursor();
      const fullText = editor.getValue();
      const lines = fullText.split("\n");
      let offset = 0;
      for (let i = 0; i < cursor.line; i++) {
        offset += lines[i].length + 1;
      }
      offset += cursor.ch;
      const verseNum = nearestVerseAtOffset(fullText, offset);
      if (verseNum === null) {
        new import_obsidian.Notice("No verse marker found near cursor.");
        return;
      }
      const fileName = (_b = (_a = plugin.app.workspace.getActiveFile()) == null ? void 0 : _a.basename) != null ? _b : "";
      const ref = `[[${fileName}#verse-${verseNum}]]`;
      void navigator.clipboard.writeText(ref).then(() => {
        new import_obsidian.Notice(`Copied: ${ref}`);
      });
    }
  });
  plugin.addCommand({
    id: "copy-verse-range-reference",
    name: "Copy verse range reference",
    editorCallback(editor) {
      var _a, _b;
      const fullText = editor.getValue();
      const from = editor.getCursor("from");
      const to = editor.getCursor("to");
      if (from.line === to.line && from.ch === to.ch) {
        new import_obsidian.Notice("Select a range spanning at least two verse markers.");
        return;
      }
      const lines = fullText.split("\n");
      const toOffset = (pos) => {
        let off = 0;
        for (let i = 0; i < pos.line; i++)
          off += lines[i].length + 1;
        return off + pos.ch;
      };
      const selFrom = toOffset(from);
      const selTo = toOffset(to);
      const range = verseRangeInSelection(fullText, selFrom, selTo);
      if (!range) {
        new import_obsidian.Notice("Selection must span at least two verse markers.");
        return;
      }
      const fileName = (_b = (_a = plugin.app.workspace.getActiveFile()) == null ? void 0 : _a.basename) != null ? _b : "";
      const ref = `[[${fileName}#verse-${range.first}:${range.last}]]`;
      void navigator.clipboard.writeText(ref).then(() => {
        new import_obsidian.Notice(`Copied: ${ref}`);
      });
    }
  });
}

// src/references.ts
var import_obsidian2 = require("obsidian");
function partToIndex2(part) {
  return part.charCodeAt(0) - "a".charCodeAt(0);
}
function verseMarkerLabel(label) {
  return `<span class="verse-marker">${label}</span>`;
}
function applyBlockquotePrefix(text, prefix) {
  if (!prefix)
    return text;
  return text.split("\n").map((line) => `${prefix}${line}`).join("\n");
}
function buildRangeCore(content, start, end, maxVerses, startPart, endPart) {
  const limit = Math.min(end, start + Math.max(maxVerses, 1) - 1);
  if (startPart === null && endPart === null) {
    const raw = getVerseRangeRawText(content, start, limit);
    if (!raw || raw.length === 0)
      return null;
    return { markdown: raw, versesUsed: limit - start + 1 };
  }
  const blocks = [];
  for (let n = start; n <= limit; n++) {
    const trimStart = n === start && startPart !== null;
    const trimEnd = n === limit && n === end && endPart !== null;
    let verseText;
    let label = `${n}`;
    if (trimStart || trimEnd) {
      const parts = getVerseParts(content, n);
      if (!parts)
        continue;
      const sliceStart = trimStart && startPart !== null ? partToIndex2(startPart) : 0;
      const sliceEnd = trimEnd && endPart !== null ? partToIndex2(endPart) + 1 : parts.length;
      if (sliceStart < 0 || sliceStart >= parts.length)
        continue;
      if (sliceEnd <= sliceStart)
        continue;
      const sliced = parts.slice(sliceStart, sliceEnd).filter((p) => p.length > 0);
      if (sliced.length === 0)
        continue;
      verseText = sliced.join(" ");
      if (trimStart)
        label = `${n}${startPart}`;
    } else {
      verseText = getVerseContent(content, n);
      if (verseText === null)
        continue;
    }
    const line = `${verseMarkerLabel(label)} ${verseText}`;
    blocks.push(applyBlockquotePrefix(line, verseBlockquotePrefix(content, n)));
  }
  if (blocks.length === 0)
    return null;
  return { markdown: blocks.join("\n\n"), versesUsed: limit - start + 1 };
}
function buildSingleCore(content, verse, part) {
  const prefix = verseBlockquotePrefix(content, verse);
  if (part !== null) {
    const verseText = getVerseContent(content, verse, part);
    if (verseText === null || verseText.length === 0)
      return null;
    const line = `${verseMarkerLabel(`${verse}${part}`)} ${verseText}`;
    return applyBlockquotePrefix(line, prefix);
  }
  const blocks = getVerseFragments(content, verse).filter((f) => f.content.length > 0).map((f) => {
    const label = f.part ? `${verse}${f.part}` : `${verse}`;
    const line = `${verseMarkerLabel(label)} ${f.content}`;
    return applyBlockquotePrefix(line, prefix);
  });
  if (blocks.length === 0)
    return null;
  return blocks.join("\n\n");
}
async function buildSegmentsPreviewMarkdown(app, file, segments, maxVerses) {
  const content = await app.vault.cachedRead(file);
  const blocks = [];
  let remaining = maxVerses;
  for (const seg of segments) {
    if (remaining <= 0)
      break;
    const isSingle = seg.start === seg.end && seg.startPart === seg.endPart;
    if (isSingle) {
      const core = buildSingleCore(content, seg.start, seg.startPart);
      if (core) {
        blocks.push(core);
        remaining -= 1;
      }
    } else {
      const core = buildRangeCore(
        content,
        seg.start,
        seg.end,
        remaining,
        seg.startPart,
        seg.endPart
      );
      if (core) {
        blocks.push(core.markdown);
        remaining -= core.versesUsed;
      }
    }
  }
  if (blocks.length === 0)
    return null;
  return appendMissingFootnoteDefinitions(blocks.join("\n\n"), content);
}
function getPagePreviewInstance(app) {
  var _a, _b, _c;
  const internal = app.internalPlugins;
  const plugin = (_c = (_a = internal == null ? void 0 : internal.getPluginById) == null ? void 0 : _a.call(internal, "page-preview")) != null ? _c : (_b = internal == null ? void 0 : internal.plugins) == null ? void 0 : _b["page-preview"];
  const instance = plugin == null ? void 0 : plugin.instance;
  if (!instance || typeof instance.onLinkHover !== "function")
    return null;
  return instance;
}
function verseFragmentOf(linktext, allowShorthand) {
  const hashIndex = linktext.indexOf("#");
  if (hashIndex === -1)
    return null;
  const fragment = linktext.slice(hashIndex + 1);
  return parseVerseSegments(fragment, allowShorthand) ? fragment : null;
}
function registerVersePagePreview(plugin) {
  try {
    const instance = getPagePreviewInstance(plugin.app);
    if (!instance)
      return;
    const original = instance.onLinkHover.bind(instance);
    const wrapped = (hoverParent, targetEl, linktext, sourcePath, ...rest) => {
      try {
        if (verseFragmentOf(linktext, plugin.settings.enableShorthandSyntax)) {
          if (plugin.settings.enableHoverPreviews) {
            openVersePopover(
              plugin,
              hoverParent,
              targetEl,
              linktext,
              sourcePath != null ? sourcePath : ""
            );
          }
          return;
        }
      } catch (e) {
      }
      return original(hoverParent, targetEl, linktext, sourcePath, ...rest);
    };
    instance.onLinkHover = wrapped;
    plugin.register(() => {
      if (instance.onLinkHover === wrapped)
        instance.onLinkHover = original;
    });
  } catch (e) {
  }
}
function openVersePopover(plugin, hoverParent, targetEl, linktext, sourcePath) {
  const allowShorthand = plugin.settings.enableShorthandSyntax;
  const hashIndex = linktext.indexOf("#");
  if (hashIndex === -1)
    return;
  const filePart = linktext.slice(0, hashIndex);
  const fragment = linktext.slice(hashIndex + 1);
  const file = plugin.app.metadataCache.getFirstLinkpathDest(filePart, sourcePath);
  if (!(file instanceof import_obsidian2.TFile))
    return;
  const current = hoverParent.hoverPopover;
  if (current && current.__verseTargetEl === targetEl)
    return;
  const popover = new import_obsidian2.HoverPopover(hoverParent, targetEl);
  popover.__verseTargetEl = targetEl;
  popover.hoverPopover = null;
  popover.hoverEl.addClass("verse-hover-preview");
  popover.hoverEl.addClass("verse-hover-measuring");
  let alive = true;
  popover.register(() => {
    alive = false;
  });
  void renderVersePopover(
    plugin,
    popover,
    () => alive,
    file,
    fragment,
    sourcePath,
    allowShorthand
  );
}
function hidePopover(popover) {
  const h = popover;
  if (typeof h.hide === "function")
    h.hide();
  else
    popover.unload();
}
async function renderVersePopover(plugin, popover, isAlive, file, fragment, sourcePath, allowShorthand) {
  var _a, _b;
  const segments = parseVerseSegments(fragment, allowShorthand);
  if (!segments)
    return;
  const markdown = await buildSegmentsPreviewMarkdown(
    plugin.app,
    file,
    segments,
    plugin.settings.hoverPreviewMaxVerses
  );
  if (!isAlive() || !markdown)
    return;
  const hoverEl = popover.hoverEl;
  const win = (_a = hoverEl.ownerDocument.defaultView) != null ? _a : window;
  let frames = 0;
  while (!hoverEl.isConnected && isAlive() && frames++ < 60) {
    await new Promise(
      (resolve) => win.requestAnimationFrame(() => resolve())
    );
  }
  if (!isAlive())
    return;
  hoverEl.empty();
  const embed = hoverEl.createDiv({ cls: "markdown-embed is-loaded" });
  const content = embed.createDiv({ cls: "markdown-embed-content" });
  const preview = content.createDiv({
    cls: "markdown-preview-view markdown-rendered"
  });
  await import_obsidian2.MarkdownRenderer.render(plugin.app, markdown, preview, file.path, popover);
  if (!isAlive())
    return;
  const openLink = embed.createEl("a", {
    cls: "markdown-embed-link",
    attr: { "aria-label": "Open link" }
  });
  (0, import_obsidian2.setIcon)(openLink, "lucide-maximize-2");
  openLink.addEventListener("click", (ev) => {
    ev.preventDefault();
    ev.stopPropagation();
    hidePopover(popover);
    void resolveVerseLink(plugin.app, file, fragment, allowShorthand);
  });
  wirePopoverAnchors(plugin, preview, popover, sourcePath);
  const targetEl = (_b = popover.__verseTargetEl) != null ? _b : null;
  if (targetEl)
    positionVersePopover(hoverEl, targetEl);
  hoverEl.removeClass("verse-hover-measuring");
}
var POPOVER_GAP_PX = 4;
var POPOVER_VIEWPORT_MARGIN_PX = 8;
function positionVersePopover(hoverEl, targetEl) {
  var _a;
  const win = (_a = hoverEl.ownerDocument.defaultView) != null ? _a : window;
  const link = targetEl.getBoundingClientRect();
  const pop = hoverEl.getBoundingClientRect();
  if (pop.width === 0 && pop.height === 0)
    return;
  const vw = win.innerWidth;
  const vh = win.innerHeight;
  const gap = POPOVER_GAP_PX;
  const margin = POPOVER_VIEWPORT_MARGIN_PX;
  let left = link.left;
  if (left + pop.width > vw - margin)
    left = vw - pop.width - margin;
  if (left < margin)
    left = margin;
  let top = link.bottom + gap;
  if (top + pop.height > vh - margin) {
    const above = link.top - pop.height - gap;
    const roomAbove = link.top;
    const roomBelow = vh - link.bottom;
    if (above >= margin && roomAbove > roomBelow)
      top = above;
    else
      top = Math.max(margin, vh - pop.height - margin);
  }
  const curLeft = parseFloat(hoverEl.style.left || "") || 0;
  const curTop = parseFloat(hoverEl.style.top || "") || 0;
  hoverEl.style.left = `${curLeft + (left - pop.left)}px`;
  hoverEl.style.top = `${curTop + (top - pop.top)}px`;
}
function wirePopoverAnchors(plugin, contentEl, popover, sourcePath) {
  var _a, _b;
  const allowShorthand = plugin.settings.enableShorthandSyntax;
  const anchors = collectVerseAnchors(contentEl, allowShorthand);
  for (const a of anchors) {
    const href = (_b = (_a = a.getAttribute("data-href")) != null ? _a : a.getAttribute("href")) != null ? _b : "";
    const hashIdx = href.indexOf("#");
    if (hashIdx === -1)
      continue;
    const filePart = href.slice(0, hashIdx);
    const fragment = href.slice(hashIdx + 1);
    const onClick = (ev) => {
      const file = plugin.app.metadataCache.getFirstLinkpathDest(
        filePart,
        sourcePath
      );
      if (!(file instanceof import_obsidian2.TFile))
        return;
      ev.preventDefault();
      ev.stopPropagation();
      hidePopover(popover);
      void resolveVerseLink(plugin.app, file, fragment, allowShorthand);
    };
    const onOver = (ev) => {
      ev.stopPropagation();
      openVersePopover(plugin, popover, a, href, sourcePath);
    };
    a.addEventListener("click", onClick);
    a.addEventListener("mouseover", onOver);
    popover.register(() => {
      a.removeEventListener("click", onClick);
      a.removeEventListener("mouseover", onOver);
    });
  }
}
async function resolveVerseLink(app, file, fragment, allowShorthand = false) {
  var _a, _b;
  const segments = parseVerseSegments(fragment, allowShorthand);
  if (!segments || segments.length === 0)
    return false;
  let startVerse = segments[0].start;
  let startPart = segments[0].startPart;
  const leaf = app.workspace.getMostRecentLeaf();
  if (!leaf)
    return false;
  const content = await app.vault.cachedRead(file);
  const flashSegments = segments.map((seg) => ({
    start: seg.start,
    startPart: partHasAnchor(content, seg.start, seg.startPart) ? seg.startPart : null,
    end: seg.end,
    endPart: partHasAnchor(content, seg.end, seg.endPart) ? seg.endPart : null
  }));
  startPart = flashSegments[0].startPart;
  const targetLine = findVerseLine(content, startVerse);
  const primaryId = startPart ? `verse-${startVerse}${startPart}` : `verse-${startVerse}`;
  const firstPart = firstFragmentPart(content, startVerse);
  const fallbackId = !startPart && firstPart ? `verse-${startVerse}${firstPart}` : `verse-${startVerse}`;
  const sameFileOpen = leaf.view instanceof import_obsidian2.MarkdownView && leaf.view.file === file;
  const anchorAlreadyMounted = sameFileOpen && (activeDocument.getElementById(primaryId) !== null || activeDocument.getElementById(fallbackId) !== null);
  const needForcedScroll = !anchorAlreadyMounted && targetLine !== null;
  const openState = needForcedScroll && targetLine !== null ? { eState: { line: targetLine } } : void 0;
  if (needForcedScroll) {
    suppressNativeFlashFor(NATIVE_FLASH_SUPPRESS_MS);
  }
  await leaf.openFile(file, openState);
  if (needForcedScroll && targetLine !== null && leaf.view instanceof import_obsidian2.MarkdownView) {
    const scrollableView = leaf.view;
    (_a = scrollableView.applyScroll) == null ? void 0 : _a.call(scrollableView, targetLine);
  }
  const anchor = (_b = await waitForElementById(primaryId, ANCHOR_WAIT_TIMEOUT_MS)) != null ? _b : activeDocument.getElementById(fallbackId);
  if (anchor) {
    window.requestAnimationFrame(() => {
      if (activeDocument.body.contains(anchor)) {
        smoothScrollAnchorToCenter(anchor);
      }
    });
  }
  flashVerseSegments(flashSegments);
  return true;
}
var ANCHOR_WAIT_TIMEOUT_MS = 1500;
function findScrollAncestor(el) {
  let parent = el.parentElement;
  while (parent) {
    const style = getComputedStyle(parent);
    const overflowY = style.overflowY;
    const scrollable = overflowY === "auto" || overflowY === "scroll";
    if (scrollable && parent.scrollHeight > parent.clientHeight) {
      return parent;
    }
    parent = parent.parentElement;
  }
  return null;
}
function smoothScrollAnchorToCenter(anchor) {
  const container = findScrollAncestor(anchor);
  const anchorRect = anchor.getBoundingClientRect();
  if (!container) {
    window.scrollTo({ top: window.scrollY, behavior: "auto" });
    const target2 = window.scrollY + anchorRect.top + anchorRect.height / 2 - window.innerHeight / 2;
    window.scrollTo({ top: target2, behavior: "smooth" });
    return;
  }
  container.scrollTo({ top: container.scrollTop, behavior: "auto" });
  const containerRect = container.getBoundingClientRect();
  const relTop = anchorRect.top - containerRect.top;
  const target = container.scrollTop + relTop + anchorRect.height / 2 - container.clientHeight / 2;
  container.scrollTo({ top: target, behavior: "smooth" });
}
var NATIVE_FLASH_SUPPRESS_MS = 5e3;
var NATIVE_FLASH_CLASSES = [
  "is-flashing",
  "is-flashing-block",
  "has-active-flash",
  "is-flash"
];
function stripNativeFlashClasses(el) {
  for (const cls of NATIVE_FLASH_CLASSES) {
    if (el.classList.contains(cls))
      el.classList.remove(cls);
  }
}
function suppressNativeFlashFor(durationMs) {
  const root = activeDocument.body;
  for (const cls of NATIVE_FLASH_CLASSES) {
    root.querySelectorAll(`.${cls}`).forEach(stripNativeFlashClasses);
  }
  const observer = new MutationObserver((mutations) => {
    for (const m of mutations) {
      if (m.type === "attributes" && m.attributeName === "class") {
        stripNativeFlashClasses(m.target);
      } else if (m.type === "childList") {
        for (const node of Array.from(m.addedNodes)) {
          if (node.nodeType !== Node.ELEMENT_NODE)
            continue;
          const el = node;
          stripNativeFlashClasses(el);
          for (const cls of NATIVE_FLASH_CLASSES) {
            el.querySelectorAll(`.${cls}`).forEach(stripNativeFlashClasses);
          }
        }
      }
    }
  });
  observer.observe(root, {
    attributes: true,
    attributeFilter: ["class"],
    childList: true,
    subtree: true
  });
  let disposed = false;
  const dispose = () => {
    if (disposed)
      return;
    disposed = true;
    observer.disconnect();
    window.clearTimeout(timer);
  };
  const timer = window.setTimeout(dispose, durationMs);
  return dispose;
}
function waitForElementById(id, timeoutMs) {
  const existing = activeDocument.getElementById(id);
  if (existing)
    return Promise.resolve(existing);
  return new Promise((resolve) => {
    let settled = false;
    const finish = (el) => {
      if (settled)
        return;
      settled = true;
      observer.disconnect();
      window.clearTimeout(timer);
      resolve(el);
    };
    const observer = new MutationObserver(() => {
      const el = activeDocument.getElementById(id);
      if (el)
        finish(el);
    });
    observer.observe(activeDocument.body, { childList: true, subtree: true });
    const timer = window.setTimeout(() => {
      finish(activeDocument.getElementById(id));
    }, timeoutMs);
  });
}
var FLASH_FADE_MS = 220;
var FLASH_HOLD_MS = 2e3;
var activeFlashSpans = [];
var flashTimer = null;
function flashVerseSegments(segments) {
  const flashRanges = buildVerseFlashRanges(segments);
  if (flashRanges.length === 0)
    return;
  if (flashTimer !== null) {
    window.clearTimeout(flashTimer);
    flashTimer = null;
  }
  unwrapFlashSpans();
  const spans = [];
  for (const fr of flashRanges) {
    const rangeSpans = wrapRangeWithSpans(fr.range, "verse-flash");
    if (rangeSpans.length > 0) {
      if (fr.capStart)
        rangeSpans[0].classList.add("verse-flash-start");
      if (fr.capEnd) {
        rangeSpans[rangeSpans.length - 1].classList.add("verse-flash-end");
      }
    }
    for (const span of rangeSpans)
      spans.push(span);
  }
  if (spans.length === 0)
    return;
  activeFlashSpans = spans;
  window.requestAnimationFrame(() => {
    for (const s of spans)
      s.classList.add("verse-flash-active");
  });
  flashTimer = window.setTimeout(() => {
    for (const s of spans)
      s.classList.remove("verse-flash-active");
    flashTimer = window.setTimeout(() => {
      if (activeFlashSpans === spans)
        unwrapFlashSpans();
      flashTimer = null;
    }, FLASH_FADE_MS);
  }, FLASH_HOLD_MS);
}
function wrapRangeWithSpans(range, className) {
  const spans = [];
  const ancestor = range.commonAncestorContainer;
  const walkRoot = ancestor.nodeType === Node.TEXT_NODE ? ancestor.parentNode : ancestor;
  if (!walkRoot)
    return spans;
  const walker = activeDocument.createTreeWalker(walkRoot, NodeFilter.SHOW_TEXT);
  const candidates = [];
  let cur;
  while (cur = walker.nextNode()) {
    const t = cur;
    if (!t.nodeValue || t.nodeValue.length === 0)
      continue;
    const owner = t.parentElement;
    if (owner && owner.closest("h1, h2, h3, h4, h5, h6"))
      continue;
    if (!/\S/.test(t.nodeValue))
      continue;
    if (range.intersectsNode(t))
      candidates.push(t);
  }
  for (const node of candidates) {
    const parent = node.parentNode;
    if (!parent)
      continue;
    const span = activeDocument.createElement("span");
    span.className = className;
    parent.insertBefore(span, node);
    span.appendChild(node);
    spans.push(span);
  }
  return spans;
}
function unwrapFlashSpans() {
  for (const span of activeFlashSpans) {
    const parent = span.parentNode;
    if (!parent)
      continue;
    while (span.firstChild)
      parent.insertBefore(span.firstChild, span);
    parent.removeChild(span);
    if (parent.nodeType === Node.ELEMENT_NODE) {
      parent.normalize();
    }
  }
  activeFlashSpans = [];
}
function anchorInSegment(n, part, seg) {
  if (n < seg.start || n > seg.end)
    return false;
  if (n === seg.start && seg.startPart !== null) {
    if (part === null)
      return false;
    if (part.charCodeAt(0) < seg.startPart.charCodeAt(0))
      return false;
  }
  if (n === seg.end && seg.endPart !== null && part !== null) {
    if (part.charCodeAt(0) > seg.endPart.charCodeAt(0))
      return false;
  }
  return true;
}
function collectInSegmentsAnchors(segments) {
  var _a;
  const all = activeDocument.querySelectorAll('[id^="verse-"]');
  const inRange = [];
  for (let i = 0; i < all.length; i++) {
    const el = all[i];
    const m = /^verse-(\d+)([a-z]+)?$/.exec(el.id);
    if (!m)
      continue;
    const n = parseInt(m[1], 10);
    const part = (_a = m[2]) != null ? _a : null;
    if (segments.some((seg) => anchorInSegment(n, part, seg)))
      inRange.push(el);
  }
  return inRange;
}
var FLASH_STOP_FOOTNOTE_SELECTORS = [
  "section.footnotes",
  ".footnotes",
  "ol.footnote-list"
];
var FLASH_STOP_HEADING_SELECTORS = ["h1", "h2", "h3", "h4", "h5", "h6"];
function findFlashStopBetween(a, b, includeHeadings) {
  const selectors = includeHeadings ? [...FLASH_STOP_FOOTNOTE_SELECTORS, ...FLASH_STOP_HEADING_SELECTORS] : FLASH_STOP_FOOTNOTE_SELECTORS;
  const candidates = activeDocument.querySelectorAll(selectors.join(","));
  for (let i = 0; i < candidates.length; i++) {
    const el = candidates[i];
    if (!(a.compareDocumentPosition(el) & Node.DOCUMENT_POSITION_FOLLOWING)) {
      continue;
    }
    if (b && !(el.compareDocumentPosition(b) & Node.DOCUMENT_POSITION_FOLLOWING)) {
      continue;
    }
    return el;
  }
  return null;
}
function buildVerseFlashRanges(segments) {
  const inRange = collectInSegmentsAnchors(segments);
  if (inRange.length === 0)
    return [];
  const allValidAnchors = [];
  const all = activeDocument.querySelectorAll('[id^="verse-"]');
  for (let i = 0; i < all.length; i++) {
    if (/^verse-\d+[a-z]*$/.test(all[i].id))
      allValidAnchors.push(all[i]);
  }
  const inRangeSet = new Set(inRange);
  const ranges = [];
  for (const anchor of inRange) {
    const idx = allValidAnchors.indexOf(anchor);
    const next = idx >= 0 ? allValidAnchors[idx + 1] : void 0;
    const prev = idx > 0 ? allValidAnchors[idx - 1] : void 0;
    const nextInSelection = next !== void 0 && inRangeSet.has(next);
    const prevInSelection = prev !== void 0 && inRangeSet.has(prev);
    const includeHeadings = !nextInSelection;
    const range = activeDocument.createRange();
    try {
      range.setStartBefore(anchor);
      const stop = findFlashStopBetween(anchor, next != null ? next : null, includeHeadings);
      if (stop) {
        range.setEndBefore(stop);
      } else if (next) {
        range.setEndBefore(next);
      } else {
        const last = activeDocument.body.lastChild;
        if (!last)
          continue;
        range.setEndAfter(last);
      }
      ranges.push({
        range,
        capStart: !prevInSelection,
        capEnd: !nextInSelection
      });
    } catch (e) {
      continue;
    }
  }
  return ranges;
}

// src/embeds.ts
var import_obsidian3 = require("obsidian");
function wrapAsDocumentBlocks(preview) {
  const doc = preview.ownerDocument;
  for (const child of Array.from(preview.children)) {
    const wrapper = doc.createElement("div");
    wrapper.className = `el-${child.tagName.toLowerCase()}`;
    preview.insertBefore(wrapper, child);
    wrapper.appendChild(child);
  }
}
var VerseEmbed = class extends import_obsidian3.Component {
  constructor(plugin, ctx, file, fragment) {
    super();
    this.plugin = plugin;
    this.ctx = ctx;
    this.file = file;
    this.fragment = fragment;
    this.renderToken = 0;
  }
  onload() {
    void this.render();
  }
  /** Obsidian calls this to (re)render when the source file changes. */
  async loadFile() {
    await this.render();
  }
  async render() {
    const myToken = ++this.renderToken;
    const allowShorthand = this.plugin.settings.enableShorthandSyntax;
    const segments = parseVerseSegments(this.fragment, allowShorthand);
    let markdown = null;
    if (segments) {
      markdown = await buildSegmentsPreviewMarkdown(
        this.plugin.app,
        this.file,
        segments,
        this.plugin.settings.hoverPreviewMaxVerses
      );
    }
    if (myToken !== this.renderToken)
      return;
    const container = this.ctx.containerEl;
    container.empty();
    container.removeClass("verse-embed-empty");
    container.addClasses(["markdown-embed", "is-loaded", "verse-embed"]);
    container.createDiv({
      cls: "embed-title markdown-embed-title",
      text: this.file.basename
    });
    if (!markdown) {
      container.addClass("verse-embed-empty");
      container.createDiv({
        cls: "markdown-embed-content",
        text: `Couldn't find "${this.fragment}"`
      });
      return;
    }
    const content = container.createDiv({ cls: "markdown-embed-content" });
    const preview = content.createDiv({
      cls: "markdown-rendered verse-embed-preview"
    });
    await import_obsidian3.MarkdownRenderer.render(
      this.plugin.app,
      markdown,
      preview,
      this.file.path,
      this
    );
    if (myToken !== this.renderToken)
      return;
    styleVerseMarkers(preview);
    wrapAsDocumentBlocks(preview);
    const link = container.createEl("a", {
      cls: "markdown-embed-link",
      attr: { "aria-label": "Open link" }
    });
    (0, import_obsidian3.setIcon)(link, "lucide-maximize-2");
    link.addEventListener("click", (ev) => {
      ev.preventDefault();
      ev.stopPropagation();
      void resolveVerseLink(
        this.plugin.app,
        this.file,
        this.fragment,
        allowShorthand
      );
    });
  }
};
function registerVerseEmbeds(plugin) {
  try {
    const registry = plugin.app.embedRegistry;
    if (!registry || typeof registry.embedByExtension !== "object")
      return;
    const original = registry.embedByExtension["md"];
    if (typeof original !== "function")
      return;
    const creator = (ctx, file, subpath) => {
      const fragment = (subpath != null ? subpath : "").replace(/^#/, "");
      if (fragment) {
        const segments = parseVerseSegments(
          fragment,
          plugin.settings.enableShorthandSyntax
        );
        if (segments)
          return new VerseEmbed(plugin, ctx, file, fragment);
      }
      return original(ctx, file, subpath);
    };
    registry.embedByExtension["md"] = creator;
    plugin.register(() => {
      registry.embedByExtension["md"] = original;
    });
  } catch (e) {
  }
}

// src/settings.ts
var import_obsidian4 = require("obsidian");
var DEFAULT_SETTINGS = {
  enableHoverPreviews: true,
  hoverPreviewMaxVerses: 20,
  enableShorthandSyntax: false
};
var VerseMarkersSettingTab = class extends import_obsidian4.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian4.Setting(containerEl).setName("Reference syntax").setHeading();
    const syntaxEl = containerEl.createEl("div", {
      cls: "setting-item-description verse-markers-syntax-ref"
    });
    syntaxEl.createEl("strong", { text: "Reference syntax:" });
    syntaxEl.createEl("br");
    syntaxEl.appendText(
      "Default \u2014 [[File#verse-3]], [[File#verse-3a]] / [[File#verse-3b]] (heading-split parts), [[File#verse-3:7]] (range)"
    );
    syntaxEl.createEl("br");
    syntaxEl.appendText(
      "Shorthand (opt-in below) \u2014 [[File#3]] / [[File#3a]] / [[File#3:7]]"
    );
    new import_obsidian4.Setting(containerEl).setName("Enable range hover previews").setDesc("Show a popover with verse content when hovering over [[FILE#verse-N:M]] links.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enableHoverPreviews).onChange(async (value) => {
        this.plugin.settings.enableHoverPreviews = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian4.Setting(containerEl).setName("Enable shorthand reference syntax").setDesc(
      'Recognize [[File#3]] and [[File#3:7]] in addition to the default [[File#verse-3]] form. Warning: enabling this will intercept links to headings literally named "3" or "3:7".'
    ).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enableShorthandSyntax).onChange(async (value) => {
        this.plugin.settings.enableShorthandSyntax = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian4.Setting(containerEl).setName("Max verses in hover preview").setDesc("Maximum number of verses to display in a range hover preview.").addText(
      (text) => text.setPlaceholder("20").setValue(String(this.plugin.settings.hoverPreviewMaxVerses)).onChange(async (value) => {
        const num = parseInt(value, 10);
        if (!isNaN(num) && num > 0) {
          this.plugin.settings.hoverPreviewMaxVerses = num;
          await this.plugin.saveSettings();
        }
      })
    );
  }
};

// src/main.ts
var VerseMarkersPlugin = class extends import_obsidian5.Plugin {
  constructor() {
    super(...arguments);
    /** Disposers for hover-preview listeners attached to rendered anchors. */
    this.hoverDisposers = [];
  }
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new VerseMarkersSettingTab(this.app, this));
    this.registerMarkdownPostProcessor((el, ctx) => {
      versePostProcessor(el, ctx);
      this.wireVerseAnchors(el);
    });
    registerVersePagePreview(this);
    registerVerseEmbeds(this);
    registerCommands(this);
    this.registerObsidianProtocolHandler("verse-markers", async (params) => {
      const verse = params["verse"];
      const filePath = params["file"];
      if (!verse || !filePath)
        return;
      const file = this.app.vault.getAbstractFileByPath(filePath);
      if (!(file instanceof import_obsidian5.TFile))
        return;
      const vm = /^(\d+)([a-z]*)$/.exec(verse);
      if (!vm)
        return;
      const verseNum = parseInt(vm[1], 10);
      const part = vm[2] || params["part"] || "";
      const fragment = part ? `verse-${verseNum}${part}` : `verse-${verseNum}`;
      await resolveVerseLink(this.app, file, fragment);
    });
  }
  onunload() {
    for (const dispose of this.hoverDisposers)
      dispose();
    this.hoverDisposers = [];
  }
  async loadSettings() {
    const data = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, data != null ? data : {});
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  /**
   * For each rendered anchor whose fragment is verse-N or verse-N:M, attach a
   * click handler that invokes our verse-aware navigator. Hover previews are
   * handled separately by the page-preview hook (registerVersePagePreview).
   */
  wireVerseAnchors(el) {
    var _a, _b;
    if (el.closest(".verse-hover-preview"))
      return;
    const allowShorthand = this.settings.enableShorthandSyntax;
    const anchors = collectVerseAnchors(el, allowShorthand);
    for (const a of anchors) {
      const href = (_b = (_a = a.getAttribute("data-href")) != null ? _a : a.getAttribute("href")) != null ? _b : "";
      const hashIdx = href.indexOf("#");
      if (hashIdx === -1)
        continue;
      const filePart = href.slice(0, hashIdx);
      const fragment = href.slice(hashIdx + 1);
      const onClick = (ev) => {
        const file = this.app.metadataCache.getFirstLinkpathDest(filePart, "");
        if (!(file instanceof import_obsidian5.TFile))
          return;
        ev.preventDefault();
        ev.stopPropagation();
        void resolveVerseLink(this.app, file, fragment, allowShorthand);
      };
      a.addEventListener("click", onClick);
      this.hoverDisposers.push(() => a.removeEventListener("click", onClick));
    }
  }
};
