/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => VerseMarkersPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian6 = require("obsidian");

// src/detection.ts
var VERSE_MARKER_REGEX = /\[\d+[a-z]*\](?=\s|$)/gm;
function getVerseRegex() {
  return new RegExp(VERSE_MARKER_REGEX.source, VERSE_MARKER_REGEX.flags);
}
var INLINE_FORMAT_DELIM = /=|[*~_]/;
function atVerseBoundary(text, index) {
  if (index <= 0)
    return true;
  let pos = index - 1;
  while (pos >= 0) {
    if (INLINE_FORMAT_DELIM.test(text.charAt(pos))) {
      pos--;
      continue;
    }
    if (text.charAt(pos) === "\\") {
      pos--;
      continue;
    }
    break;
  }
  if (pos < 0)
    return true;
  const prev = text.charAt(pos);
  return prev === ">" || /\s/.test(prev);
}
function execVerseMarker(re, text) {
  let m;
  while ((m = re.exec(text)) !== null) {
    if (atVerseBoundary(text, m.index))
      return m;
  }
  return null;
}
function hasVerseMarker(text) {
  return execVerseMarker(getVerseRegex(), text) !== null;
}
function parseMarkerToken(token) {
  const m = /^\[(\d+)([a-z]*)\]$/.exec(token);
  if (!m)
    return { number: NaN, part: null };
  return { number: parseInt(m[1], 10), part: m[2] === "" ? null : m[2] };
}
function partToIndex(part) {
  return part.charCodeAt(0) - "a".charCodeAt(0);
}
function scanMarkers(text) {
  const re = getVerseRegex();
  const hits = [];
  let m;
  while ((m = execVerseMarker(re, text)) !== null) {
    const { number, part } = parseMarkerToken(m[0]);
    hits.push({
      number,
      part,
      index: m.index,
      afterMarker: m.index + m[0].length
    });
  }
  return hits;
}
var HEADING_LINE_REGEX = /^\s*#{1,6}\s+\S.*$/;
var VERSE_BREAK_TOKEN = "[//]";
function findVerseBreakIndex(text, from = 0) {
  let pos = from;
  while (pos < text.length) {
    const idx = text.indexOf(VERSE_BREAK_TOKEN, pos);
    if (idx === -1)
      return -1;
    if (idx > 0 && text[idx - 1] === "\\") {
      pos = idx + VERSE_BREAK_TOKEN.length;
      continue;
    }
    return idx;
  }
  return -1;
}
function isVerseBreakLine(line) {
  return /^\s*(?:>\s?)*\[\/\/\]\s*$/.test(line);
}
function charOffsetForLine(text, lineIndex) {
  if (lineIndex <= 0)
    return 0;
  let line = 0;
  for (let i = 0; i < text.length; i++) {
    if (line === lineIndex)
      return i;
    if (text[i] === "\n")
      line++;
  }
  return text.length;
}
function isFollowedByFootnoteRef(text, markerEnd) {
  return /^\s+\[\^[^\]\s]+\]/.test(text.slice(markerEnd));
}
function verseProcessStateAt(text, endOffset) {
  const state = { inVerseSpan: false, inVerseMode: true };
  let pos = 0;
  const limit = Math.min(endOffset, text.length);
  while (pos < limit) {
    const slice = text.slice(pos, limit);
    const brRel = findVerseBreakIndex(slice);
    const brIdx = brRel === -1 ? -1 : pos + brRel;
    const m = execVerseMarker(getVerseRegex(), slice);
    const markerIdx = m ? pos + m.index : -1;
    if (brIdx === -1 && markerIdx === -1)
      break;
    if (markerIdx === -1 || brIdx !== -1 && brIdx < markerIdx) {
      if (state.inVerseSpan)
        state.inVerseMode = !state.inVerseMode;
      pos = brIdx + VERSE_BREAK_TOKEN.length;
    } else {
      state.inVerseSpan = true;
      state.inVerseMode = true;
      pos = markerIdx + m[0].length;
    }
  }
  return state;
}
function stripBlockquoteMarker(line) {
  return line.replace(/^\s*>\s?/, "");
}
function stripEditorialBreaks(raw) {
  const parts = [];
  let inVerse = true;
  let pos = 0;
  while (pos < raw.length) {
    const br = findVerseBreakIndex(raw, pos);
    if (br === -1) {
      if (inVerse)
        parts.push(raw.slice(pos));
      break;
    }
    if (inVerse)
      parts.push(raw.slice(pos, br));
    inVerse = !inVerse;
    pos = br + VERSE_BREAK_TOKEN.length;
  }
  return parts.join("");
}
function paragraphStartAt(text, offset) {
  let lineStart = text.lastIndexOf("\n", offset - 1) + 1;
  while (lineStart > 0) {
    const prevLineEnd = lineStart - 1;
    const prevLineStart = text.lastIndexOf("\n", prevLineEnd - 1) + 1;
    const prevLine = text.slice(prevLineStart, prevLineEnd);
    const stripped = stripBlockquoteMarker(prevLine);
    if (/^\s*$/.test(stripped) || HEADING_LINE_REGEX.test(stripped))
      break;
    lineStart = prevLineStart;
  }
  return lineStart;
}
function highlightOpenAt(text, offset) {
  const start = paragraphStartAt(text, offset);
  let open = false;
  let inInlineCode = false;
  let inFence = false;
  let i = start;
  while (i < offset) {
    if (text.slice(i, i + 3) === "```") {
      if (!inInlineCode) {
        inFence = !inFence;
        i += 3;
        continue;
      }
    }
    if (!inFence) {
      if (text[i] === "`") {
        inInlineCode = !inInlineCode;
        i++;
        continue;
      }
      if (!inInlineCode && text.slice(i, i + 2) === "==") {
        if (i > start && text[i - 1] === "\\") {
          i += 2;
          continue;
        }
        open = !open;
        i += 2;
        continue;
      }
    }
    i++;
  }
  return open;
}
function prependHighlightOpener(slice) {
  const nl = slice.indexOf("\n");
  const firstLine = nl === -1 ? slice : slice.slice(0, nl);
  const rest = nl === -1 ? "" : slice.slice(nl);
  const lead = /^(\s*(?:>\s?)*)/.exec(firstLine);
  const prefix = lead ? lead[1] : "";
  return `${prefix}==${firstLine.slice(prefix.length)}${rest}`;
}
function balanceHighlights(slice, fullText, sliceStart, sliceEnd) {
  let result = slice;
  if (highlightOpenAt(fullText, sliceStart)) {
    result = prependHighlightOpener(result);
  }
  if (highlightOpenAt(fullText, sliceEnd)) {
    result = `${result}==`;
  }
  return result;
}
function splitSegmentByFootnotes(segment) {
  const re = new RegExp(FOOTNOTE_REF_REGEX.source, "g");
  const parts = [];
  let lastIndex = 0;
  let m;
  while ((m = re.exec(segment)) !== null) {
    const cut = m.index + m[0].length;
    if (/\S/.test(segment.slice(lastIndex, m.index)) && /\S/.test(segment.slice(cut))) {
      parts.push(segment.slice(lastIndex, cut));
      lastIndex = cut;
    }
  }
  parts.push(segment.slice(lastIndex));
  return parts;
}
function versePartSegments(rawContent) {
  const lines = rawContent.split("\n").map(stripBlockquoteMarker);
  const segments = [[]];
  for (const line of lines) {
    if (HEADING_LINE_REGEX.test(line)) {
      segments.push([]);
    } else {
      segments[segments.length - 1].push(line);
    }
  }
  return segments.map(
    (group) => splitSegmentByFootnotes(group.join("\n")).map((part) => part.trim())
  );
}
function splitVerseParts(rawContent) {
  return versePartSegments(rawContent).flat();
}
function findVerseSpan(text, verseNumber) {
  const re = getVerseRegex();
  let spanStart = -1;
  let spanEnd = text.length;
  let match;
  while ((match = execVerseMarker(re, text)) !== null) {
    const num = parseMarkerToken(match[0]).number;
    const afterMarker = match.index + match[0].length;
    if (spanStart === -1 && num === verseNumber) {
      if (text[afterMarker] !== " ")
        return null;
      spanStart = afterMarker + 1;
    } else if (spanStart !== -1) {
      spanEnd = match.index;
      break;
    }
  }
  if (spanStart === -1)
    return null;
  return { start: spanStart, end: spanEnd };
}
function verseModeSourceIntervals(text, from, to) {
  const out = [];
  let inVerse = true;
  let pos = from;
  while (pos < to) {
    const br = findVerseBreakIndex(text, pos);
    if (br === -1 || br >= to) {
      if (inVerse && pos < to && /\S/.test(text.slice(pos, to))) {
        out.push({ from: pos, to });
      }
      break;
    }
    if (inVerse && br > pos && /\S/.test(text.slice(pos, br))) {
      out.push({ from: pos, to: br });
    }
    inVerse = !inVerse;
    pos = br + VERSE_BREAK_TOKEN.length;
  }
  return out;
}
var FOOTNOTE_REF_REGEX = /\[\^([^\]\s]+)\](?!:)/g;
var FOOTNOTE_DEF_HEAD_REGEX = /^\[\^([^\]\s]+)\]:/;
function footnoteDefinitionsBlockStart(text, searchFrom) {
  let offset = 0;
  const lines = text.split("\n");
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    if (offset >= searchFrom && FOOTNOTE_DEF_HEAD_REGEX.test(stripBlockquoteMarker(line))) {
      return offset;
    }
    offset += line.length + (i < lines.length - 1 ? 1 : 0);
  }
  return null;
}
function mergeAdjacentSourceRanges(ranges) {
  if (ranges.length === 0)
    return ranges;
  const sorted = [...ranges].sort((a, b) => a.from - b.from);
  const merged = [sorted[0]];
  for (let i = 1; i < sorted.length; i++) {
    const prev = merged[merged.length - 1];
    const cur = sorted[i];
    if (cur.from <= prev.to) {
      prev.to = Math.max(prev.to, cur.to);
    } else {
      merged.push({ ...cur });
    }
  }
  return merged;
}
function trimTrailingWhitespaceRange(text, from, to) {
  let end = to;
  while (end > from && /\s/.test(text[end - 1]))
    end--;
  if (end <= from || !/\S/.test(text.slice(from, end)))
    return null;
  return { from, to: end };
}
function verseNumberAtMarker(text, offset) {
  const m = execVerseMarker(getVerseRegex(), text.slice(offset));
  if (!m || m.index !== 0)
    return null;
  return parseMarkerToken(m[0]).number;
}
function isEmptyTail(text, afterLine, before) {
  let tail = text.slice(afterLine, before);
  const foot = footnoteDefinitionsBlockStart(text, afterLine);
  if (foot !== null && foot < before) {
    tail = text.slice(afterLine, foot);
  }
  return !/\S/.test(tail);
}
function trailingHeadingStartInSpan(text, searchFrom, searchBefore) {
  let offset = 0;
  const lines = text.split("\n");
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    if (offset >= searchFrom && offset < searchBefore && HEADING_LINE_REGEX.test(stripBlockquoteMarker(line))) {
      const afterLine = offset + line.length + (i < lines.length - 1 ? 1 : 0);
      if (isEmptyTail(text, afterLine, searchBefore)) {
        return offset;
      }
    }
    offset += line.length + (i < lines.length - 1 ? 1 : 0);
  }
  return null;
}
function flashSpanEndForVerse(text, span, inRange) {
  let end = span.end;
  const nextInSelection = end < text.length && (() => {
    const nextNum = verseNumberAtMarker(text, end);
    return nextNum !== null && inRange.has(nextNum);
  })();
  if (!nextInSelection) {
    const heading = trailingHeadingStartInSpan(text, span.start, end);
    if (heading !== null)
      end = heading;
  }
  const footStart = footnoteDefinitionsBlockStart(text, span.start);
  if (footStart !== null && footStart < end)
    end = footStart;
  return end;
}
function markerTokenRangeForVerse(text, verseNumber) {
  const re = getVerseRegex();
  let m;
  while ((m = execVerseMarker(re, text)) !== null) {
    if (parseMarkerToken(m[0]).number === verseNumber) {
      return { from: m.index, to: m.index + m[0].length };
    }
  }
  return null;
}
function getVerseFlashRuns(text, segments) {
  var _a;
  const inRange = /* @__PURE__ */ new Set();
  for (const seg of segments) {
    for (let n = seg.start; n <= seg.end; n++)
      inRange.add(n);
  }
  const runs = [];
  for (const seg of segments) {
    const parts = [];
    for (let n = seg.start; n <= seg.end; n++) {
      const span = findVerseSpan(text, n);
      if (!span)
        continue;
      const marker = markerTokenRangeForVerse(text, n);
      const flashFrom = (_a = marker == null ? void 0 : marker.from) != null ? _a : span.start;
      const spanEnd = flashSpanEndForVerse(text, span, inRange);
      parts.push(...verseModeSourceIntervals(text, flashFrom, spanEnd));
    }
    const ranges = mergeAdjacentSourceRanges(parts);
    if (ranges.length === 0)
      continue;
    const lastIdx = ranges.length - 1;
    const trimmed = trimTrailingWhitespaceRange(
      text,
      ranges[lastIdx].from,
      ranges[lastIdx].to
    );
    if (!trimmed)
      continue;
    ranges[lastIdx] = trimmed;
    runs.push({ ranges, capStart: true, capEnd: true });
  }
  return runs;
}
function getVerseParts(text, verseNumber) {
  const span = findVerseSpan(text, verseNumber);
  if (!span)
    return null;
  return splitVerseParts(
    stripEditorialBreaks(text.slice(span.start, span.end))
  );
}
function getVerseFragments(text, verseNumber) {
  const hits = scanMarkers(text);
  const fragments = [];
  for (let i = 0; i < hits.length; i++) {
    if (hits[i].number !== verseNumber)
      continue;
    if (text[hits[i].afterMarker] !== " ")
      continue;
    const contentStart = hits[i].afterMarker + 1;
    const hardEnd = i + 1 < hits.length ? hits[i + 1].index : text.length;
    const raw = balanceHighlights(
      text.slice(contentStart, hardEnd),
      text,
      contentStart,
      hardEnd
    );
    const content = splitVerseParts(stripEditorialBreaks(raw)).filter((p) => p.length > 0).join(" ");
    fragments.push({ part: hits[i].part, content });
  }
  return fragments;
}
function getVerseContent(text, verseNumber, part = null) {
  const fragments = getVerseFragments(text, verseNumber);
  if (fragments.length === 0)
    return null;
  if (part !== null) {
    const explicit = fragments.find((f) => f.part === part);
    if (explicit)
      return explicit.content;
    if (fragments.length === 1 && fragments[0].part === null) {
      const span = findVerseSpan(text, verseNumber);
      if (!span)
        return null;
      const parts = splitVerseParts(
        stripEditorialBreaks(text.slice(span.start, span.end))
      );
      const idx = partToIndex(part);
      if (idx < 0 || idx >= parts.length)
        return null;
      return parts[idx];
    }
    return null;
  }
  return fragments.map((f) => f.content).filter((c) => c.length > 0).join(" ");
}
function verseBlockquotePrefix(text, verseNumber) {
  const re = getVerseRegex();
  let match;
  while ((match = execVerseMarker(re, text)) !== null) {
    if (parseMarkerToken(match[0]).number !== verseNumber)
      continue;
    const lineStart = text.lastIndexOf("\n", match.index - 1) + 1;
    const prefix = /^(\s*(?:>\s?)+)/.exec(text.slice(lineStart, match.index));
    return prefix ? prefix[1] : "";
  }
  return "";
}
function getVerseRangeRawText(text, start, end) {
  const hits = scanMarkers(text);
  let firstIdx = -1;
  let lastIdx = -1;
  for (let i = 0; i < hits.length; i++) {
    if (hits[i].number >= start && hits[i].number <= end) {
      if (firstIdx === -1)
        firstIdx = i;
      lastIdx = i;
    }
  }
  if (firstIdx === -1)
    return null;
  const startPos = lineLeadStart(text, hits[firstIdx].index);
  const contentEnd = lastIdx + 1 < hits.length ? lineLeadStart(text, hits[lastIdx + 1].index) : text.length;
  const sliceEnd = contentEnd;
  let raw = text.slice(startPos, sliceEnd);
  const trimmedLen = raw.trimEnd().length;
  raw = raw.slice(0, trimmedLen);
  raw = balanceHighlights(raw, text, startPos, startPos + trimmedLen);
  raw = stripEditorialBreaks(raw);
  return stripTrailingHeadingsBeforeNextVerse(raw);
}
function lineLeadStart(text, markerIndex) {
  const lineStart = text.lastIndexOf("\n", markerIndex - 1) + 1;
  let lead = text.slice(lineStart, markerIndex);
  while (lead.length > 0 && INLINE_FORMAT_DELIM.test(lead.charAt(lead.length - 1))) {
    lead = lead.slice(0, -1);
  }
  return /^\s*(?:>\s?)*$/.test(lead) ? lineStart : markerIndex;
}
function stripTrailingHeadingsBeforeNextVerse(raw) {
  const lines = raw.split("\n");
  let end = lines.length;
  while (end > 0) {
    let i = end - 1;
    while (i >= 0 && /^\s*$/.test(stripBlockquoteMarker(lines[i])))
      i--;
    if (i < 0) {
      end = 0;
      break;
    }
    if (HEADING_LINE_REGEX.test(stripBlockquoteMarker(lines[i]))) {
      end = i;
      continue;
    }
    break;
  }
  return lines.slice(0, end).join("\n").trimEnd();
}
function appendMissingFootnoteDefinitions(slice, fullText) {
  const referenced = /* @__PURE__ */ new Set();
  let m;
  const refRe = new RegExp(FOOTNOTE_REF_REGEX.source, FOOTNOTE_REF_REGEX.flags);
  while ((m = refRe.exec(slice)) !== null) {
    referenced.add(m[1]);
  }
  if (referenced.size === 0)
    return slice;
  const sliceLines = slice.split("\n");
  for (const line of sliceLines) {
    const head = FOOTNOTE_DEF_HEAD_REGEX.exec(line);
    if (head)
      referenced.delete(head[1]);
  }
  if (referenced.size === 0)
    return slice;
  const fullLines = fullText.split("\n");
  const appended = [];
  for (let i = 0; i < fullLines.length; i++) {
    const head = FOOTNOTE_DEF_HEAD_REGEX.exec(fullLines[i]);
    if (!head)
      continue;
    if (!referenced.has(head[1]))
      continue;
    const block = [fullLines[i]];
    let j = i + 1;
    while (j < fullLines.length) {
      const next = fullLines[j];
      if (next === "" || /^[ \t]/.test(next)) {
        block.push(next);
        j++;
      } else {
        break;
      }
    }
    while (block.length > 0 && block[block.length - 1] === "")
      block.pop();
    appended.push(block.join("\n"));
    referenced.delete(head[1]);
    if (referenced.size === 0)
      break;
  }
  if (appended.length === 0)
    return slice;
  return `${slice}

${appended.join("\n\n")}`;
}
function findVerseLine(text, verseNumber) {
  const re = getVerseRegex();
  let match;
  while ((match = execVerseMarker(re, text)) !== null) {
    const num = parseMarkerToken(match[0]).number;
    if (num === verseNumber) {
      let line = 0;
      for (let i = 0; i < match.index; i++) {
        if (text.charCodeAt(i) === 10)
          line++;
      }
      return line;
    }
  }
  return null;
}
function continuationPartAnchor(text, blockStartLine) {
  const lines = text.split("\n");
  let headingCount = 0;
  let verseNumber = null;
  for (let i = blockStartLine - 1; i >= 0; i--) {
    const stripped = stripBlockquoteMarker(lines[i]);
    if (findVerseBreakIndex(lines[i]) !== -1)
      return null;
    if (HEADING_LINE_REGEX.test(stripped)) {
      headingCount++;
      continue;
    }
    const marker = execVerseMarker(getVerseRegex(), lines[i]);
    if (marker) {
      verseNumber = parseMarkerToken(marker[0]).number;
      break;
    }
  }
  if (verseNumber === null || headingCount === 0)
    return null;
  let index = headingCount;
  const span = findVerseSpan(text, verseNumber);
  if (span) {
    const segments = versePartSegments(text.slice(span.start, span.end));
    for (let s = 0; s < headingCount && s < segments.length; s++) {
      index += segments[s].length - 1;
    }
  }
  return `verse-${verseNumber}${String.fromCharCode(97 + index)}`;
}
function partHasAnchor(text, verseNumber, part) {
  if (part === null)
    return true;
  if (scanMarkers(text).some((h) => h.number === verseNumber && h.part === part)) {
    return true;
  }
  const span = findVerseSpan(text, verseNumber);
  if (!span)
    return false;
  const segments = versePartSegments(text.slice(span.start, span.end));
  const target = partToIndex(part);
  let segmentStart = 0;
  for (const segment of segments) {
    if (segmentStart === target)
      return true;
    segmentStart += segment.length;
  }
  return false;
}
function firstFragmentPart(text, verseNumber) {
  const first = scanMarkers(text).find((h) => h.number === verseNumber);
  return first ? first.part : null;
}
var SEGMENT_SOURCE = String.raw`\d+[a-z]*(?::\d+[a-z]*)?`;
function parseVerseSegments(fragment, allowShorthand = false) {
  let core;
  if (fragment.startsWith("verse-")) {
    core = fragment.slice("verse-".length);
  } else if (allowShorthand) {
    core = fragment;
  } else {
    return null;
  }
  if (core.length === 0)
    return null;
  const segRe = new RegExp(`^(\\d+)([a-z]*)(?::(\\d+)([a-z]*))?$`);
  const segments = [];
  for (const piece of core.split("/")) {
    const m = segRe.exec(piece);
    if (!m)
      return null;
    const start = parseInt(m[1], 10);
    const startPart = m[2] === "" ? null : m[2];
    if (m[3] !== void 0) {
      segments.push({
        start,
        startPart,
        end: parseInt(m[3], 10),
        endPart: m[4] === "" ? null : m[4]
      });
    } else {
      segments.push({ start, startPart, end: start, endPart: startPart });
    }
  }
  return segments;
}
var VERSE_FRAGMENT_TEST_STRICT = new RegExp(
  `^verse-${SEGMENT_SOURCE}(?:/${SEGMENT_SOURCE})*$`
);
var VERSE_FRAGMENT_TEST_LOOSE = new RegExp(
  `^(?:verse-)?${SEGMENT_SOURCE}(?:/${SEGMENT_SOURCE})*$`
);

// src/postprocessor.ts
var SKIP_TAGS = /* @__PURE__ */ new Set([
  "A",
  "CODE",
  "PRE",
  "MATH",
  "MJX-CONTAINER",
  "TABLE",
  "IMG"
]);
var SKIP_CLASSES = [".math"];
var EMBED_SKIP_CLASSES = [".internal-embed", ".external-embed"];
function isInsideSkipped(node, skipEmbeds = true) {
  let current = node.parentNode;
  while (current !== null) {
    if (current.nodeType === Node.ELEMENT_NODE) {
      const el = current;
      if (SKIP_TAGS.has(el.tagName))
        return true;
      for (const cls of SKIP_CLASSES) {
        if (el.matches(cls))
          return true;
      }
      if (skipEmbeds) {
        for (const cls of EMBED_SKIP_CLASSES) {
          if (el.matches(cls))
            return true;
        }
      }
    }
    current = current.parentNode;
  }
  return false;
}
function appendVerseText(fragment, text, state) {
  if (text.length === 0)
    return;
  if (state.inVerseSpan && !state.inVerseMode) {
    const span = activeDocument.createElement("span");
    span.className = "verse-editorial";
    span.appendChild(activeDocument.createTextNode(text));
    fragment.appendChild(span);
    return;
  }
  fragment.appendChild(activeDocument.createTextNode(text));
}
function appendVerseMarker(fragment, token) {
  const { number, part } = parseMarkerToken(token);
  const label = `${number}${part != null ? part : ""}`;
  const markerEl = activeDocument.createElement("span");
  markerEl.className = "verse-marker";
  markerEl.id = `verse-${label}`;
  markerEl.textContent = label;
  fragment.appendChild(markerEl);
}
function nextInlineToken(text, from) {
  const slice = text.slice(from);
  const brRel = findVerseBreakIndex(slice);
  const brIdx = brRel === -1 ? -1 : from + brRel;
  const m = execVerseMarker(getVerseRegex(), slice);
  const markerIdx = m ? from + m.index : -1;
  if (brIdx === -1 && markerIdx === -1)
    return null;
  if (markerIdx === -1 || brIdx !== -1 && brIdx < markerIdx) {
    return { index: brIdx, length: VERSE_BREAK_TOKEN.length, kind: "break" };
  }
  return { index: markerIdx, length: m[0].length, kind: "marker", token: m[0] };
}
function processTextNode(textNode, state) {
  var _a, _b;
  if ((_a = textNode.parentElement) == null ? void 0 : _a.closest(".verse-editorial, .verse-marker")) {
    return false;
  }
  const text = (_b = textNode.nodeValue) != null ? _b : "";
  const hasToken = nextInlineToken(text, 0) !== null;
  if (!hasToken && !(state.inVerseSpan && !state.inVerseMode))
    return false;
  const parent = textNode.parentNode;
  if (!parent)
    return false;
  if (!hasToken) {
    const span = activeDocument.createElement("span");
    span.className = "verse-editorial";
    span.appendChild(activeDocument.createTextNode(text));
    parent.replaceChild(span, textNode);
    return true;
  }
  const fragment = activeDocument.createDocumentFragment();
  let lastIndex = 0;
  let pos = 0;
  while (pos < text.length) {
    const hit = nextInlineToken(text, pos);
    if (!hit)
      break;
    if (hit.index > lastIndex) {
      appendVerseText(fragment, text.slice(lastIndex, hit.index), state);
    }
    if (hit.kind === "marker") {
      appendVerseMarker(fragment, hit.token);
      state.inVerseSpan = true;
      state.inVerseMode = true;
    } else if (state.inVerseSpan) {
      state.inVerseMode = !state.inVerseMode;
    }
    lastIndex = hit.index + hit.length;
    pos = lastIndex;
  }
  if (lastIndex < text.length) {
    appendVerseText(fragment, text.slice(lastIndex), state);
  }
  parent.replaceChild(fragment, textNode);
  return true;
}
function isEditorialContinuationBlock(blockText, state) {
  return state.inVerseSpan && !state.inVerseMode && !hasVerseMarker(blockText) && !isVerseBreakLine(blockText);
}
function collectTextNodes(el, skipEmbeds = true) {
  const result = [];
  const walker = activeDocument.createTreeWalker(el, NodeFilter.SHOW_TEXT);
  let node;
  while ((node = walker.nextNode()) !== null) {
    const textNode = node;
    if (!isInsideSkipped(textNode, skipEmbeds)) {
      result.push(textNode);
    }
  }
  return result;
}
function styleVerseMarkers(el) {
  const textNodes = collectTextNodes(el, false);
  const state = { inVerseSpan: false, inVerseMode: true };
  for (const tn of textNodes) {
    processTextNode(tn, state);
  }
}
function collectVerseAnchors(el, allowShorthand = false) {
  var _a, _b;
  const test = allowShorthand ? VERSE_FRAGMENT_TEST_LOOSE : VERSE_FRAGMENT_TEST_STRICT;
  const result = [];
  const anchors = el.getElementsByTagName("a");
  for (let i = 0; i < anchors.length; i++) {
    const a = anchors[i];
    const href = (_b = (_a = a.getAttribute("data-href")) != null ? _a : a.getAttribute("href")) != null ? _b : "";
    const hashIdx = href.indexOf("#");
    if (hashIdx === -1)
      continue;
    const fragment = href.slice(hashIdx + 1);
    if (test.test(fragment)) {
      result.push(a);
    }
  }
  return result;
}
function partAnchorForBlock(el, ctx) {
  const info = ctx.getSectionInfo(el);
  if (!info)
    return null;
  const sourceLines = info.text.split("\n");
  const blockText = sourceLines.slice(info.lineStart, info.lineEnd + 1).join("\n");
  if (hasVerseMarker(blockText))
    return null;
  return continuationPartAnchor(info.text, info.lineStart);
}
function injectPartAnchor(el, id) {
  if (el.querySelector(`#${CSS.escape(id)}`))
    return;
  const anchor = activeDocument.createElement("span");
  anchor.id = id;
  anchor.className = "verse-part-anchor";
  anchor.setAttribute("aria-hidden", "true");
  el.insertBefore(anchor, el.firstChild);
}
function hideVerseBreakBlock(el, ctx) {
  const info = ctx.getSectionInfo(el);
  if (!info)
    return;
  const blockText = info.text.split("\n").slice(info.lineStart, info.lineEnd + 1).join("\n");
  if (!isVerseBreakLine(blockText))
    return;
  el.addClass("verse-break");
  el.empty();
  el.setAttr("aria-hidden", "true");
}
function versePostProcessor(el, ctx) {
  let state = { inVerseSpan: false, inVerseMode: true };
  let blockText = "";
  if (ctx) {
    const info = ctx.getSectionInfo(el);
    if (info) {
      const lines = info.text.split("\n");
      blockText = lines.slice(info.lineStart, info.lineEnd + 1).join("\n");
      state = verseProcessStateAt(
        info.text,
        charOffsetForLine(info.text, info.lineStart)
      );
    }
  }
  if (isEditorialContinuationBlock(blockText, state)) {
    el.addClass("verse-editorial");
    if (ctx)
      hideVerseBreakBlock(el, ctx);
    const partId = ctx ? partAnchorForBlock(el, ctx) : null;
    if (partId)
      injectPartAnchor(el, partId);
    return;
  }
  const textNodes = collectTextNodes(el);
  for (const tn of textNodes) {
    processTextNode(tn, state);
  }
  if (ctx) {
    hideVerseBreakBlock(el, ctx);
    const partId = partAnchorForBlock(el, ctx);
    if (partId)
      injectPartAnchor(el, partId);
  }
}

// src/commands.ts
var import_obsidian = require("obsidian");
function markerLabel(token) {
  const { number, part } = parseMarkerToken(token);
  return `${number}${part != null ? part : ""}`;
}
function nearestVerseAtOffset(text, cursorOffset) {
  const re = getVerseRegex();
  let match;
  let best = null;
  let bestDist = Infinity;
  while ((match = execVerseMarker(re, text)) !== null) {
    const start = match.index;
    const end = start + match[0].length;
    const dist = Math.min(Math.abs(cursorOffset - start), Math.abs(cursorOffset - end));
    if (dist < bestDist) {
      bestDist = dist;
      best = markerLabel(match[0]);
    }
  }
  return best;
}
function verseRangeInSelection(text, selFrom, selTo) {
  const slice = text.slice(selFrom, selTo);
  const re = getVerseRegex();
  const found = [];
  let match;
  while ((match = execVerseMarker(re, slice)) !== null) {
    found.push(markerLabel(match[0]));
  }
  if (found.length < 2)
    return null;
  return { first: found[0], last: found[found.length - 1] };
}
function registerCommands(plugin) {
  plugin.addCommand({
    id: "copy-verse-reference",
    name: "Copy verse reference",
    editorCallback(editor) {
      var _a, _b;
      const cursor = editor.getCursor();
      const fullText = editor.getValue();
      const lines = fullText.split("\n");
      let offset = 0;
      for (let i = 0; i < cursor.line; i++) {
        offset += lines[i].length + 1;
      }
      offset += cursor.ch;
      const verseNum = nearestVerseAtOffset(fullText, offset);
      if (verseNum === null) {
        new import_obsidian.Notice("No verse marker found near cursor.");
        return;
      }
      const fileName = (_b = (_a = plugin.app.workspace.getActiveFile()) == null ? void 0 : _a.basename) != null ? _b : "";
      const ref = `[[${fileName}#verse-${verseNum}]]`;
      void navigator.clipboard.writeText(ref).then(() => {
        new import_obsidian.Notice(`Copied: ${ref}`);
      });
    }
  });
  plugin.addCommand({
    id: "copy-verse-range-reference",
    name: "Copy verse range reference",
    editorCallback(editor) {
      var _a, _b;
      const fullText = editor.getValue();
      const from = editor.getCursor("from");
      const to = editor.getCursor("to");
      if (from.line === to.line && from.ch === to.ch) {
        new import_obsidian.Notice("Select a range spanning at least two verse markers.");
        return;
      }
      const lines = fullText.split("\n");
      const toOffset = (pos) => {
        let off = 0;
        for (let i = 0; i < pos.line; i++)
          off += lines[i].length + 1;
        return off + pos.ch;
      };
      const selFrom = toOffset(from);
      const selTo = toOffset(to);
      const range = verseRangeInSelection(fullText, selFrom, selTo);
      if (!range) {
        new import_obsidian.Notice("Selection must span at least two verse markers.");
        return;
      }
      const fileName = (_b = (_a = plugin.app.workspace.getActiveFile()) == null ? void 0 : _a.basename) != null ? _b : "";
      const ref = `[[${fileName}#verse-${range.first}:${range.last}]]`;
      void navigator.clipboard.writeText(ref).then(() => {
        new import_obsidian.Notice(`Copied: ${ref}`);
      });
    }
  });
}

// src/references.ts
var import_obsidian3 = require("obsidian");

// src/highlights.ts
var HEADING_LINE_REGEX2 = /^\s*#{1,6}\s+\S.*$/;
function stripBlockquoteMarker2(line) {
  return line.replace(/^\s*>\s?/, "");
}
function findHighlightRanges(text, baseOffset = 0) {
  const ranges = [];
  let paraLines = [];
  let paraStart = 0;
  let cursor = 0;
  let inFence = false;
  const flushPara = () => {
    if (paraLines.length === 0)
      return;
    const para = paraLines.join("\n");
    findHighlightPairsInParagraph(para, baseOffset + paraStart, ranges);
    paraLines = [];
  };
  for (const line of text.split("\n")) {
    const lineStart = cursor;
    cursor += line.length + 1;
    if (line.trimStart().startsWith("```")) {
      flushPara();
      inFence = !inFence;
      continue;
    }
    if (inFence)
      continue;
    const stripped = stripBlockquoteMarker2(line);
    if (/^\s*$/.test(stripped) || HEADING_LINE_REGEX2.test(stripped)) {
      flushPara();
      continue;
    }
    if (paraLines.length === 0)
      paraStart = lineStart;
    paraLines.push(line);
  }
  flushPara();
  return ranges;
}
function findHighlightPairsInParagraph(paragraph, baseOffset, out) {
  let inInlineCode = false;
  let i = 0;
  while (i < paragraph.length) {
    if (paragraph[i] === "`") {
      inInlineCode = !inInlineCode;
      i++;
      continue;
    }
    if (!inInlineCode && paragraph.slice(i, i + 2) === "==") {
      if (i > 0 && paragraph[i - 1] === "\\") {
        i += 2;
        continue;
      }
      const innerStart = i + 2;
      const close = findClosingHighlight(paragraph, innerStart, inInlineCode);
      if (close !== -1) {
        out.push({ start: baseOffset + innerStart, end: baseOffset + close });
        i = close + 2;
        continue;
      }
    }
    i++;
  }
}
function findClosingHighlight(paragraph, from, startInCode) {
  let inInlineCode = startInCode;
  let i = from;
  while (i < paragraph.length) {
    if (paragraph[i] === "`") {
      inInlineCode = !inInlineCode;
      i++;
      continue;
    }
    if (!inInlineCode && paragraph.slice(i, i + 2) === "==") {
      if (i > from && paragraph[i - 1] === "\\") {
        i += 2;
        continue;
      }
      return i;
    }
    i++;
  }
  return -1;
}
function convertHighlightSyntaxToHtml(text) {
  const out = [];
  let paraLines = [];
  let inFence = false;
  const flushPara = () => {
    if (paraLines.length > 0) {
      out.push(convertHighlightInParagraph(paraLines.join("\n")));
      paraLines = [];
    }
  };
  for (const line of text.split("\n")) {
    if (line.trimStart().startsWith("```")) {
      flushPara();
      inFence = !inFence;
      out.push(line);
      continue;
    }
    if (inFence) {
      out.push(line);
      continue;
    }
    const stripped = stripBlockquoteMarker2(line);
    if (/^\s*$/.test(stripped) || HEADING_LINE_REGEX2.test(stripped)) {
      flushPara();
      out.push(line);
      continue;
    }
    paraLines.push(line);
  }
  flushPara();
  return out.join("\n");
}
function convertHighlightInParagraph(paragraph) {
  let result = "";
  let inInlineCode = false;
  let i = 0;
  while (i < paragraph.length) {
    if (paragraph[i] === "`") {
      inInlineCode = !inInlineCode;
      result += paragraph[i];
      i++;
      continue;
    }
    if (!inInlineCode && paragraph.slice(i, i + 2) === "==") {
      if (i > 0 && paragraph[i - 1] === "\\") {
        result += "==";
        i += 2;
        continue;
      }
      const innerStart = i + 2;
      const close = findClosingHighlight(paragraph, innerStart, inInlineCode);
      if (close !== -1) {
        result += `<mark>${paragraph.slice(innerStart, close)}</mark>`;
        i = close + 2;
        continue;
      }
    }
    result += paragraph[i];
    i++;
  }
  return result;
}

// src/flashLivePreview.ts
var import_state = require("@codemirror/state");
var import_view2 = require("@codemirror/view");

// src/nativeFlash.ts
var import_obsidian2 = require("obsidian");
var import_view = require("@codemirror/view");
var VERSE_HIGHLIGHT_ACTIVE_CLASS = "verse-highlight-active";
function isVerseHighlightActive() {
  return activeDocument.body.classList.contains(VERSE_HIGHLIGHT_ACTIVE_CLASS);
}
function setVerseHighlightActive(active) {
  activeDocument.body.classList.toggle(VERSE_HIGHLIGHT_ACTIVE_CLASS, active);
}
function cmView(editor) {
  var _a;
  return (_a = editor.cm) != null ? _a : null;
}
function scrollEditorWithoutFlash(editor, range, center = false) {
  const view = cmView(editor);
  if (!view)
    return;
  const from = editor.posToOffset(range.from);
  const to = editor.posToOffset(range.to);
  const anchor = center ? Math.round((from + to) / 2) : from;
  view.dispatch({
    effects: import_view.EditorView.scrollIntoView(anchor, {
      y: center ? "center" : "nearest"
    })
  });
}
async function scrollReadingViewToLine(mdView, line) {
  var _a, _b;
  const v = mdView;
  const renderer = (_a = v.previewMode) == null ? void 0 : _a.renderer;
  if (renderer == null ? void 0 : renderer.applyScrollDelayed) {
    renderer.applyScrollDelayed(line, { highlight: false });
  } else if (renderer == null ? void 0 : renderer.applyScroll) {
    renderer.applyScroll(line);
  } else if ((_b = v.previewMode) == null ? void 0 : _b.applyScroll) {
    v.previewMode.applyScroll(line);
  } else if (v.applyScroll) {
    v.applyScroll(line);
  }
  await new Promise((resolve) => {
    window.requestAnimationFrame(() => window.requestAnimationFrame(() => resolve()));
  });
}
function patchEditor(editor) {
  var _a;
  const ed = editor;
  if (ed.__verseMarkersFlashPatched)
    return;
  ed.__verseMarkersFlashPatched = true;
  const origHighlights = (_a = ed.addHighlights) == null ? void 0 : _a.bind(ed);
  if (origHighlights) {
    ed.addHighlights = (ranges, style, removePrevious, range) => {
      if (isVerseHighlightActive() && style === "is-flashing")
        return;
      return origHighlights(ranges, style, removePrevious, range);
    };
  }
  const origScroll = ed.scrollIntoView.bind(ed);
  ed.scrollIntoView = (range, center) => {
    if (isVerseHighlightActive()) {
      scrollEditorWithoutFlash(ed, range, center != null ? center : false);
      return;
    }
    return origScroll(range, center);
  };
}
function patchMarkdownView(view) {
  (view == null ? void 0 : view.editor) && patchEditor(view.editor);
}
function registerNativeFlashPrevention(plugin) {
  plugin.app.workspace.iterateAllLeaves((leaf) => {
    if (leaf.view instanceof import_obsidian2.MarkdownView)
      patchMarkdownView(leaf.view);
  });
  plugin.registerEvent(
    plugin.app.workspace.on("active-leaf-change", () => {
      patchMarkdownView(plugin.app.workspace.getActiveViewOfType(import_obsidian2.MarkdownView));
    })
  );
  plugin.registerEvent(
    plugin.app.workspace.on("file-open", () => {
      patchMarkdownView(plugin.app.workspace.getActiveViewOfType(import_obsidian2.MarkdownView));
    })
  );
}

// src/highlightDismiss.ts
var VERSE_FLASH_AUTO_MS = 2e3;
var dismissHandlers = [];
var getSettings = null;
var autoDismissTimer = null;
function configureVerseHighlightBehavior(getter) {
  getSettings = getter;
}
function keepHighlightUntilClick() {
  var _a;
  return (_a = getSettings == null ? void 0 : getSettings().keepHighlightUntilClick) != null ? _a : false;
}
function clearAutoDismissTimer() {
  if (autoDismissTimer !== null) {
    window.clearTimeout(autoDismissTimer);
    autoDismissTimer = null;
  }
}
function onVerseHighlightDismiss(handler) {
  dismissHandlers.push(handler);
  return () => {
    const i = dismissHandlers.indexOf(handler);
    if (i !== -1)
      dismissHandlers.splice(i, 1);
  };
}
function dismissVerseHighlight() {
  clearAutoDismissTimer();
  for (const handler of dismissHandlers)
    handler();
  setVerseHighlightActive(false);
}
function notifyVerseHighlightShown() {
  clearAutoDismissTimer();
  if (keepHighlightUntilClick())
    return;
  autoDismissTimer = window.setTimeout(() => {
    dismissVerseHighlight();
    autoDismissTimer = null;
  }, VERSE_FLASH_AUTO_MS);
}
function registerVerseHighlightDismiss(plugin) {
  plugin.registerDomEvent(
    activeDocument,
    "mousedown",
    (ev) => {
      if (!keepHighlightUntilClick())
        return;
      const target = ev.target;
      if (isVerseNavigationTarget(target))
        return;
      dismissVerseHighlight();
    },
    { capture: true }
  );
}
function isVerseNavigationTarget(target) {
  var _a, _b;
  const link = target.closest(
    "a.internal-link, a.cm-underline, .cm-link, span.cm-link"
  );
  if (!link)
    return false;
  const href = (_b = (_a = link.getAttribute("data-href")) != null ? _a : link.getAttribute("href")) != null ? _b : "";
  const hashIdx = href.indexOf("#");
  if (hashIdx === -1)
    return false;
  return href.slice(hashIdx + 1).startsWith("verse-");
}

// src/flashLivePreview.ts
var FLASH_FADE_MS = 220;
var setVerseFlashEffect = import_state.StateEffect.define();
var activeSpec = null;
function marksFromRuns(runs) {
  const marks = [];
  for (const run of runs) {
    for (let i = 0; i < run.ranges.length; i++) {
      const r = run.ranges[i];
      marks.push({
        from: r.from,
        to: r.to,
        capStart: run.capStart && i === 0,
        capEnd: run.capEnd && i === run.ranges.length - 1
      });
    }
  }
  return normalizeGlobalCaps(marks);
}
function normalizeGlobalCaps(marks) {
  if (marks.length <= 1)
    return marks;
  let firstIdx = 0;
  let lastIdx = 0;
  for (let i = 1; i < marks.length; i++) {
    if (marks[i].from < marks[firstIdx].from)
      firstIdx = i;
    if (marks[i].to > marks[lastIdx].to)
      lastIdx = i;
  }
  return marks.map((m, i) => ({
    ...m,
    capStart: m.capStart && i === firstIdx,
    capEnd: m.capEnd && i === lastIdx
  }));
}
function lastCappedChar(text, from, to) {
  let i = to - 1;
  while (i >= from && /\s/.test(text[i]))
    i--;
  return i >= from ? i : to - 1;
}
function flashClassMid(phase) {
  return phase === "active" ? "verse-flash-cm verse-flash-cm-active" : "verse-flash-cm";
}
function addCappedMark(builder, mark, phase, text, globalEndChar) {
  const { from, to, capStart, capEnd } = mark;
  if (to <= from)
    return;
  const mid = flashClassMid(phase);
  const endChar = capEnd ? globalEndChar : -1;
  if (to - from === 1) {
    const caps = [
      capStart && "verse-flash-cm-start",
      capEnd && endChar === from && "verse-flash-cm-end"
    ].filter(Boolean);
    builder.add(from, to, import_view2.Decoration.mark({ class: [mid, ...caps].join(" ") }));
    return;
  }
  let pos = from;
  if (capStart) {
    builder.add(
      pos,
      pos + 1,
      import_view2.Decoration.mark({ class: `${mid} verse-flash-cm-start` })
    );
    pos++;
  }
  const bodyEnd = capEnd && endChar >= pos ? endChar : to;
  if (bodyEnd > pos) {
    builder.add(pos, bodyEnd, import_view2.Decoration.mark({ class: mid }));
  }
  if (capEnd && endChar >= from && endChar < to) {
    builder.add(
      endChar,
      endChar + 1,
      import_view2.Decoration.mark({ class: `${mid} verse-flash-cm-end` })
    );
    if (endChar + 1 < to) {
      builder.add(endChar + 1, to, import_view2.Decoration.mark({ class: mid }));
    }
  }
}
function flashClassesForWidget(from, to) {
  if (!activeSpec)
    return "";
  for (const m of activeSpec.marks) {
    if (m.from >= to || m.to <= from)
      continue;
    const parts = ["verse-flash-cm"];
    if (activeSpec.phase === "active")
      parts.push("verse-flash-cm-active");
    if (m.capStart && from <= m.from)
      parts.push("verse-flash-cm-start");
    if (m.capEnd && to >= m.to)
      parts.push("verse-flash-cm-end");
    return parts.join(" ");
  }
  return "";
}
var verseFlashField = import_state.StateField.define({
  create() {
    return import_view2.Decoration.none;
  },
  update(deco, tr) {
    for (const e of tr.effects) {
      if (e.is(setVerseFlashEffect)) {
        activeSpec = e.value;
        if (!e.value || e.value.marks.length === 0) {
          return import_view2.Decoration.none;
        }
        const doc = tr.state.doc.toString();
        const marks = e.value.marks;
        const globalEndChar = lastCappedChar(
          doc,
          0,
          Math.max(...marks.map((m) => m.to))
        );
        const builder = new import_state.RangeSetBuilder();
        for (const mark of marks) {
          addCappedMark(builder, mark, e.value.phase, doc, globalEndChar);
        }
        return builder.finish();
      }
    }
    return deco.map(tr.changes);
  },
  provide: (f) => import_view2.EditorView.decorations.from(f)
});
function verseFlashExtension() {
  return verseFlashField;
}
var fadeTimer = null;
var activeEditor = null;
var activeMarks = [];
function editorView(editor) {
  const cm = editor.cm;
  return cm != null ? cm : null;
}
function clearLivePreviewFlash(editor, fadeOut = true) {
  if (fadeTimer !== null) {
    window.clearTimeout(fadeTimer);
    fadeTimer = null;
  }
  const view = editor ? editorView(editor) : activeEditor ? editorView(activeEditor) : null;
  if (!view) {
    activeEditor = null;
    activeMarks = [];
    activeSpec = null;
    return;
  }
  if (!fadeOut) {
    activeEditor = null;
    activeMarks = [];
    activeSpec = null;
    view.dispatch({ effects: setVerseFlashEffect.of(null) });
    return;
  }
  if (activeMarks.length === 0) {
    activeEditor = null;
    activeSpec = null;
    view.dispatch({ effects: setVerseFlashEffect.of(null) });
    return;
  }
  view.dispatch({
    effects: setVerseFlashEffect.of({ marks: activeMarks, phase: "inactive" })
  });
  fadeTimer = window.setTimeout(() => {
    view.dispatch({ effects: setVerseFlashEffect.of(null) });
    fadeTimer = null;
    activeEditor = null;
    activeMarks = [];
    activeSpec = null;
  }, FLASH_FADE_MS);
}
function flashVerseSegmentsInEditor(editor, content, segments) {
  const view = editorView(editor);
  if (!view)
    return;
  const runs = getVerseFlashRuns(content, segments);
  const marks = marksFromRuns(runs);
  if (marks.length === 0) {
    setVerseHighlightActive(false);
    return;
  }
  clearLivePreviewFlash(editor, false);
  activeEditor = editor;
  activeMarks = marks;
  setVerseHighlightActive(true);
  const dispatch = (phase) => {
    view.dispatch({ effects: setVerseFlashEffect.of({ marks, phase }) });
  };
  dispatch("inactive");
  window.requestAnimationFrame(() => {
    dispatch("active");
    notifyVerseHighlightShown();
  });
}
function clearActiveLivePreviewFlash(fadeOut = true) {
  clearLivePreviewFlash(activeEditor, fadeOut);
}

// src/references.ts
function partToIndex2(part) {
  return part.charCodeAt(0) - "a".charCodeAt(0);
}
function verseMarkerLabel(label) {
  return `<span class="verse-marker">${label}</span>`;
}
function applyBlockquotePrefix(text, prefix) {
  if (!prefix)
    return text;
  return text.split("\n").map((line) => `${prefix}${line}`).join("\n");
}
function buildRangeCore(content, start, end, maxVerses, startPart, endPart) {
  const limit = Math.min(end, start + Math.max(maxVerses, 1) - 1);
  if (startPart === null && endPart === null) {
    const raw = getVerseRangeRawText(content, start, limit);
    if (!raw || raw.length === 0)
      return null;
    return { markdown: raw, versesUsed: limit - start + 1 };
  }
  const blocks = [];
  for (let n = start; n <= limit; n++) {
    const trimStart = n === start && startPart !== null;
    const trimEnd = n === limit && n === end && endPart !== null;
    let verseText;
    let label = `${n}`;
    if (trimStart || trimEnd) {
      const parts = getVerseParts(content, n);
      if (!parts)
        continue;
      const sliceStart = trimStart && startPart !== null ? partToIndex2(startPart) : 0;
      const sliceEnd = trimEnd && endPart !== null ? partToIndex2(endPart) + 1 : parts.length;
      if (sliceStart < 0 || sliceStart >= parts.length)
        continue;
      if (sliceEnd <= sliceStart)
        continue;
      const sliced = parts.slice(sliceStart, sliceEnd).filter((p) => p.length > 0);
      if (sliced.length === 0)
        continue;
      verseText = sliced.join(" ");
      if (trimStart)
        label = `${n}${startPart}`;
    } else {
      verseText = getVerseContent(content, n);
      if (verseText === null)
        continue;
    }
    const line = `${verseMarkerLabel(label)} ${verseText}`;
    blocks.push(applyBlockquotePrefix(line, verseBlockquotePrefix(content, n)));
  }
  if (blocks.length === 0)
    return null;
  return { markdown: blocks.join("\n\n"), versesUsed: limit - start + 1 };
}
function buildSingleCore(content, verse, part) {
  const prefix = verseBlockquotePrefix(content, verse);
  if (part !== null) {
    const verseText = getVerseContent(content, verse, part);
    if (verseText === null || verseText.length === 0)
      return null;
    const line = `${verseMarkerLabel(`${verse}${part}`)} ${verseText}`;
    return applyBlockquotePrefix(line, prefix);
  }
  const fragments = getVerseFragments(content, verse);
  if (fragments.length === 0)
    return null;
  if (fragments.length === 1 && fragments[0].part === null) {
    const raw = getVerseRangeRawText(content, verse, verse);
    if (raw && raw.length > 0) {
      return applyBlockquotePrefix(raw, prefix);
    }
  }
  const blocks = fragments.filter((f) => f.content.length > 0).map((f) => {
    const label = f.part ? `${verse}${f.part}` : `${verse}`;
    const line = `${verseMarkerLabel(label)} ${f.content}`;
    return applyBlockquotePrefix(line, prefix);
  });
  if (blocks.length === 0)
    return null;
  return blocks.join("\n\n");
}
async function buildSegmentsPreviewMarkdown(app, file, segments, maxVerses) {
  const content = await app.vault.cachedRead(file);
  const blocks = [];
  let remaining = maxVerses;
  for (const seg of segments) {
    if (remaining <= 0)
      break;
    const isSingle = seg.start === seg.end && seg.startPart === seg.endPart;
    if (isSingle) {
      const core = buildSingleCore(content, seg.start, seg.startPart);
      if (core) {
        blocks.push(core);
        remaining -= 1;
      }
    } else {
      const core = buildRangeCore(
        content,
        seg.start,
        seg.end,
        remaining,
        seg.startPart,
        seg.endPart
      );
      if (core) {
        blocks.push(core.markdown);
        remaining -= core.versesUsed;
      }
    }
  }
  if (blocks.length === 0)
    return null;
  return appendMissingFootnoteDefinitions(blocks.join("\n\n"), content);
}
function getPagePreviewInstance(app) {
  var _a, _b, _c;
  const internal = app.internalPlugins;
  const plugin = (_c = (_a = internal == null ? void 0 : internal.getPluginById) == null ? void 0 : _a.call(internal, "page-preview")) != null ? _c : (_b = internal == null ? void 0 : internal.plugins) == null ? void 0 : _b["page-preview"];
  const instance = plugin == null ? void 0 : plugin.instance;
  if (!instance || typeof instance.onLinkHover !== "function")
    return null;
  return instance;
}
function verseFragmentOf(linktext, allowShorthand) {
  const hashIndex = linktext.indexOf("#");
  if (hashIndex === -1)
    return null;
  const fragment = linktext.slice(hashIndex + 1);
  return parseVerseSegments(fragment, allowShorthand) ? fragment : null;
}
function registerVersePagePreview(plugin) {
  try {
    const instance = getPagePreviewInstance(plugin.app);
    if (!instance)
      return;
    const original = instance.onLinkHover.bind(instance);
    const wrapped = (hoverParent, targetEl, linktext, sourcePath, ...rest) => {
      try {
        if (verseFragmentOf(linktext, plugin.settings.enableShorthandSyntax)) {
          if (plugin.settings.enableHoverPreviews) {
            openVersePopover(
              plugin,
              hoverParent,
              targetEl,
              linktext,
              sourcePath != null ? sourcePath : ""
            );
          }
          return;
        }
      } catch (e) {
      }
      return original(hoverParent, targetEl, linktext, sourcePath, ...rest);
    };
    instance.onLinkHover = wrapped;
    plugin.register(() => {
      if (instance.onLinkHover === wrapped)
        instance.onLinkHover = original;
    });
  } catch (e) {
  }
}
function registerVerseLinkNavigation(plugin) {
  const { workspace } = plugin.app;
  const original = workspace.openLinkText.bind(workspace);
  workspace.openLinkText = async (linktext, sourcePath, newLeaf, openViewState) => {
    const allowShorthand = plugin.settings.enableShorthandSyntax;
    const fragment = verseFragmentOf(linktext, allowShorthand);
    if (fragment) {
      const hashIdx = linktext.indexOf("#");
      const filePart = linktext.slice(0, hashIdx);
      const file = plugin.app.metadataCache.getFirstLinkpathDest(
        filePart,
        sourcePath
      );
      if (file instanceof import_obsidian3.TFile) {
        const handled = await resolveVerseLink(
          plugin.app,
          file,
          fragment,
          allowShorthand,
          { newLeaf }
        );
        if (handled)
          return;
      }
    }
    return original(linktext, sourcePath, newLeaf, openViewState);
  };
  plugin.register(() => {
    workspace.openLinkText = original;
  });
}
function openVersePopover(plugin, hoverParent, targetEl, linktext, sourcePath) {
  const allowShorthand = plugin.settings.enableShorthandSyntax;
  const hashIndex = linktext.indexOf("#");
  if (hashIndex === -1)
    return;
  const filePart = linktext.slice(0, hashIndex);
  const fragment = linktext.slice(hashIndex + 1);
  const file = plugin.app.metadataCache.getFirstLinkpathDest(filePart, sourcePath);
  if (!(file instanceof import_obsidian3.TFile))
    return;
  const current = hoverParent.hoverPopover;
  if (current && current.__verseTargetEl === targetEl)
    return;
  const popover = new import_obsidian3.HoverPopover(hoverParent, targetEl);
  popover.__verseTargetEl = targetEl;
  popover.hoverPopover = null;
  popover.hoverEl.addClass("verse-hover-preview");
  popover.hoverEl.addClass("verse-hover-measuring");
  let alive = true;
  popover.register(() => {
    alive = false;
  });
  void renderVersePopover(
    plugin,
    popover,
    () => alive,
    file,
    fragment,
    sourcePath,
    allowShorthand
  );
}
function hidePopover(popover) {
  const h = popover;
  if (typeof h.hide === "function")
    h.hide();
  else
    popover.unload();
}
async function renderVersePopover(plugin, popover, isAlive, file, fragment, sourcePath, allowShorthand) {
  var _a, _b;
  const segments = parseVerseSegments(fragment, allowShorthand);
  if (!segments)
    return;
  const markdown = await buildSegmentsPreviewMarkdown(
    plugin.app,
    file,
    segments,
    plugin.settings.hoverPreviewMaxVerses
  );
  if (!isAlive() || !markdown)
    return;
  const hoverEl = popover.hoverEl;
  const win = (_a = hoverEl.ownerDocument.defaultView) != null ? _a : window;
  let frames = 0;
  while (!hoverEl.isConnected && isAlive() && frames++ < 60) {
    await new Promise(
      (resolve) => win.requestAnimationFrame(() => resolve())
    );
  }
  if (!isAlive())
    return;
  hoverEl.empty();
  const embed = hoverEl.createDiv({ cls: "markdown-embed is-loaded" });
  const content = embed.createDiv({ cls: "markdown-embed-content" });
  const preview = content.createDiv({
    cls: "markdown-preview-view markdown-rendered"
  });
  await import_obsidian3.MarkdownRenderer.render(
    plugin.app,
    convertHighlightSyntaxToHtml(markdown),
    preview,
    file.path,
    popover
  );
  if (!isAlive())
    return;
  const openLink = embed.createEl("a", {
    cls: "markdown-embed-link",
    attr: { "aria-label": "Open link" }
  });
  (0, import_obsidian3.setIcon)(openLink, "lucide-maximize-2");
  openLink.addEventListener("click", (ev) => {
    ev.preventDefault();
    ev.stopPropagation();
    hidePopover(popover);
    void resolveVerseLink(plugin.app, file, fragment, allowShorthand);
  });
  wirePopoverAnchors(plugin, preview, popover, sourcePath);
  const targetEl = (_b = popover.__verseTargetEl) != null ? _b : null;
  if (targetEl)
    positionVersePopover(hoverEl, targetEl);
  hoverEl.removeClass("verse-hover-measuring");
}
var POPOVER_GAP_PX = 4;
var POPOVER_VIEWPORT_MARGIN_PX = 8;
function positionVersePopover(hoverEl, targetEl) {
  var _a;
  const win = (_a = hoverEl.ownerDocument.defaultView) != null ? _a : window;
  const link = targetEl.getBoundingClientRect();
  const pop = hoverEl.getBoundingClientRect();
  if (pop.width === 0 && pop.height === 0)
    return;
  const vw = win.innerWidth;
  const vh = win.innerHeight;
  const gap = POPOVER_GAP_PX;
  const margin = POPOVER_VIEWPORT_MARGIN_PX;
  let left = link.left;
  if (left + pop.width > vw - margin)
    left = vw - pop.width - margin;
  if (left < margin)
    left = margin;
  let top = link.bottom + gap;
  if (top + pop.height > vh - margin) {
    const above = link.top - pop.height - gap;
    const roomAbove = link.top;
    const roomBelow = vh - link.bottom;
    if (above >= margin && roomAbove > roomBelow)
      top = above;
    else
      top = Math.max(margin, vh - pop.height - margin);
  }
  const curLeft = parseFloat(hoverEl.style.left || "") || 0;
  const curTop = parseFloat(hoverEl.style.top || "") || 0;
  hoverEl.style.left = `${curLeft + (left - pop.left)}px`;
  hoverEl.style.top = `${curTop + (top - pop.top)}px`;
}
function wirePopoverAnchors(plugin, contentEl, popover, sourcePath) {
  var _a, _b;
  const allowShorthand = plugin.settings.enableShorthandSyntax;
  const anchors = collectVerseAnchors(contentEl, allowShorthand);
  for (const a of anchors) {
    const href = (_b = (_a = a.getAttribute("data-href")) != null ? _a : a.getAttribute("href")) != null ? _b : "";
    const hashIdx = href.indexOf("#");
    if (hashIdx === -1)
      continue;
    const filePart = href.slice(0, hashIdx);
    const fragment = href.slice(hashIdx + 1);
    const onClick = (ev) => {
      const file = plugin.app.metadataCache.getFirstLinkpathDest(
        filePart,
        sourcePath
      );
      if (!(file instanceof import_obsidian3.TFile))
        return;
      ev.preventDefault();
      ev.stopPropagation();
      hidePopover(popover);
      void resolveVerseLink(plugin.app, file, fragment, allowShorthand);
    };
    const onOver = (ev) => {
      ev.stopPropagation();
      openVersePopover(plugin, popover, a, href, sourcePath);
    };
    a.addEventListener("click", onClick);
    a.addEventListener("mouseover", onOver);
    popover.register(() => {
      a.removeEventListener("click", onClick);
      a.removeEventListener("mouseover", onOver);
    });
  }
}
function markdownViewForFile(app, leaf, file) {
  if (leaf.view instanceof import_obsidian3.MarkdownView && leaf.view.file === file) {
    return leaf.view;
  }
  const active = app.workspace.getActiveViewOfType(import_obsidian3.MarkdownView);
  if ((active == null ? void 0 : active.file) === file)
    return active;
  return null;
}
function readingPreviewRoot(view) {
  var _a;
  return (_a = view.containerEl.querySelector(".markdown-preview-view")) != null ? _a : view.contentEl;
}
function verseAnchorIn(root, id) {
  try {
    return root.querySelector(`#${CSS.escape(id)}`);
  } catch (e) {
    return root.querySelector(`#${id}`);
  }
}
function verseAnchorMounted(root, primaryId, fallbackId) {
  return verseAnchorIn(root, primaryId) !== null || verseAnchorIn(root, fallbackId) !== null;
}
async function resolveVerseLink(app, file, fragment, allowShorthand = false, options) {
  var _a, _b, _c;
  const segments = parseVerseSegments(fragment, allowShorthand);
  if (!segments || segments.length === 0)
    return false;
  let startVerse = segments[0].start;
  let startPart = segments[0].startPart;
  const activeMd = app.workspace.getActiveViewOfType(import_obsidian3.MarkdownView);
  const leaf = (options == null ? void 0 : options.newLeaf) ? app.workspace.getLeaf(true) : (_a = activeMd == null ? void 0 : activeMd.leaf) != null ? _a : app.workspace.getMostRecentLeaf();
  if (!leaf)
    return false;
  const content = await app.vault.cachedRead(file);
  const flashSegments = segments.map((seg) => ({
    start: seg.start,
    startPart: partHasAnchor(content, seg.start, seg.startPart) ? seg.startPart : null,
    end: seg.end,
    endPart: partHasAnchor(content, seg.end, seg.endPart) ? seg.endPart : null
  }));
  startPart = flashSegments[0].startPart;
  const targetLine = findVerseLine(content, startVerse);
  const primaryId = startPart ? `verse-${startVerse}${startPart}` : `verse-${startVerse}`;
  const firstPart = firstFragmentPart(content, startVerse);
  const fallbackId = !startPart && firstPart ? `verse-${startVerse}${firstPart}` : `verse-${startVerse}`;
  const mdViewBefore = leaf.view instanceof import_obsidian3.MarkdownView ? leaf.view : null;
  const isLivePreviewBefore = (mdViewBefore == null ? void 0 : mdViewBefore.getMode()) === "source" && mdViewBefore.file === file;
  const sameFileOpen = (mdViewBefore == null ? void 0 : mdViewBefore.file) === file;
  const anchorAlreadyMounted = sameFileOpen && !isLivePreviewBefore && mdViewBefore !== null && verseAnchorMounted(
    readingPreviewRoot(mdViewBefore),
    primaryId,
    fallbackId
  );
  const needForcedScroll = !anchorAlreadyMounted && targetLine !== null;
  setVerseHighlightActive(true);
  await leaf.openFile(file);
  const mdView = markdownViewForFile(app, leaf, file);
  const isLivePreview = (mdView == null ? void 0 : mdView.getMode()) === "source";
  if (needForcedScroll && targetLine !== null && mdView && isLivePreview) {
    const pos = { line: targetLine, ch: 0 };
    mdView.editor.setCursor(pos);
    scrollEditorWithoutFlash(mdView.editor, { from: pos, to: pos }, true);
  }
  if (isLivePreview && mdView) {
    const runFlash = () => {
      if (targetLine !== null) {
        const pos = { line: targetLine, ch: 0 };
        mdView.editor.setCursor(pos);
        scrollEditorWithoutFlash(mdView.editor, { from: pos, to: pos }, true);
      }
      flashVerseSegmentsInEditor(
        mdView.editor,
        mdView.editor.getValue(),
        flashSegments
      );
    };
    window.requestAnimationFrame(() => {
      window.requestAnimationFrame(runFlash);
    });
  } else if (mdView) {
    const previewRoot = readingPreviewRoot(mdView);
    if (targetLine !== null && needForcedScroll) {
      await scrollReadingViewToLine(mdView, targetLine);
    }
    let anchor = (_b = await waitForElementById(
      primaryId,
      ANCHOR_WAIT_TIMEOUT_MS,
      previewRoot
    )) != null ? _b : verseAnchorIn(previewRoot, fallbackId);
    if (!anchor && targetLine !== null) {
      await scrollReadingViewToLine(mdView, targetLine);
      anchor = (_c = await waitForElementById(
        primaryId,
        ANCHOR_WAIT_TIMEOUT_MS,
        previewRoot
      )) != null ? _c : verseAnchorIn(previewRoot, fallbackId);
    }
    if (anchor) {
      const scrollTarget = anchor;
      window.requestAnimationFrame(() => {
        if (previewRoot.contains(scrollTarget)) {
          smoothScrollAnchorToCenter(scrollTarget);
        }
      });
    }
    flashVerseSegments(flashSegments, previewRoot);
  }
  return true;
}
var ANCHOR_WAIT_TIMEOUT_MS = 1500;
function findScrollAncestor(el) {
  let parent = el.parentElement;
  while (parent) {
    const style = getComputedStyle(parent);
    const overflowY = style.overflowY;
    const scrollable = overflowY === "auto" || overflowY === "scroll";
    if (scrollable && parent.scrollHeight > parent.clientHeight) {
      return parent;
    }
    parent = parent.parentElement;
  }
  return null;
}
function smoothScrollAnchorToCenter(anchor) {
  const container = findScrollAncestor(anchor);
  const anchorRect = anchor.getBoundingClientRect();
  if (!container) {
    window.scrollTo({ top: window.scrollY, behavior: "auto" });
    const target2 = window.scrollY + anchorRect.top + anchorRect.height / 2 - window.innerHeight / 2;
    window.scrollTo({ top: target2, behavior: "smooth" });
    return;
  }
  container.scrollTo({ top: container.scrollTop, behavior: "auto" });
  const containerRect = container.getBoundingClientRect();
  const relTop = anchorRect.top - containerRect.top;
  const target = container.scrollTop + relTop + anchorRect.height / 2 - container.clientHeight / 2;
  container.scrollTo({ top: target, behavior: "smooth" });
}
function waitForElementById(id, timeoutMs, root) {
  const existing = verseAnchorIn(root, id);
  if (existing)
    return Promise.resolve(existing);
  const observeTarget = root instanceof Document ? root.body : root;
  return new Promise((resolve) => {
    let settled = false;
    const finish = (el) => {
      if (settled)
        return;
      settled = true;
      observer.disconnect();
      window.clearTimeout(timer);
      resolve(el);
    };
    const observer = new MutationObserver(() => {
      const el = verseAnchorIn(root, id);
      if (el)
        finish(el);
    });
    observer.observe(observeTarget, { childList: true, subtree: true });
    const timer = window.setTimeout(() => {
      finish(verseAnchorIn(root, id));
    }, timeoutMs);
  });
}
var FLASH_FADE_MS2 = 220;
var FLASH_SKIP_INLINE = "h1,h2,h3,h4,h5,h6,.verse-editorial";
var activeFlashSpans = [];
var flashFadeTimer = null;
function clearReadingViewHighlight(fadeOut = true) {
  if (flashFadeTimer !== null) {
    window.clearTimeout(flashFadeTimer);
    flashFadeTimer = null;
  }
  const spans = activeFlashSpans;
  if (spans.length === 0)
    return;
  if (!fadeOut) {
    unwrapFlashSpans();
    if (activeFlashSpans.length === 0)
      setVerseHighlightActive(false);
    return;
  }
  for (const s of spans)
    s.classList.remove("verse-flash-active");
  flashFadeTimer = window.setTimeout(() => {
    if (activeFlashSpans === spans) {
      unwrapFlashSpans();
      setVerseHighlightActive(false);
    }
    flashFadeTimer = null;
  }, FLASH_FADE_MS2);
}
function flashVerseSegments(segments, root) {
  const flashRanges = buildVerseFlashRanges(segments, root);
  if (flashRanges.length === 0)
    return;
  clearReadingViewHighlight(false);
  const spans = [];
  for (const fr of flashRanges) {
    const rangeSpans = wrapRangeWithSpans(fr.range, "verse-flash", fr.capEnd);
    if (rangeSpans.length > 0) {
      if (fr.capStart)
        rangeSpans[0].classList.add("verse-flash-start");
      if (fr.capEnd) {
        rangeSpans[rangeSpans.length - 1].classList.add("verse-flash-end");
      }
    }
    for (const span of rangeSpans)
      spans.push(span);
  }
  if (spans.length === 0)
    return;
  activeFlashSpans = spans;
  setVerseHighlightActive(true);
  window.requestAnimationFrame(() => {
    for (const s of spans)
      s.classList.add("verse-flash-active");
    notifyVerseHighlightShown();
  });
}
function wrapRangeWithSpans(range, className, trimTrailingEnd = false) {
  const spans = [];
  const ancestor = range.commonAncestorContainer;
  const walkRoot = ancestor.nodeType === Node.TEXT_NODE ? ancestor.parentNode : ancestor;
  if (!walkRoot)
    return spans;
  const walker = activeDocument.createTreeWalker(walkRoot, NodeFilter.SHOW_TEXT);
  const candidates = [];
  let cur;
  while (cur = walker.nextNode()) {
    const t = cur;
    if (!t.nodeValue || t.nodeValue.length === 0)
      continue;
    const owner = t.parentElement;
    if (owner && owner.closest(FLASH_SKIP_INLINE))
      continue;
    if (range.intersectsNode(t))
      candidates.push(t);
  }
  if (trimTrailingEnd) {
    while (candidates.length > 0) {
      const last = candidates[candidates.length - 1];
      if (!last.nodeValue) {
        candidates.pop();
        continue;
      }
      if (!/\S/.test(last.nodeValue)) {
        candidates.pop();
        continue;
      }
      const trimmedLen = last.nodeValue.replace(/\s+$/, "").length;
      if (trimmedLen === 0) {
        candidates.pop();
        continue;
      }
      if (trimmedLen < last.nodeValue.length) {
        last.splitText(trimmedLen);
      }
      break;
    }
  }
  for (let i = 0; i < candidates.length; i++) {
    const node = candidates[i];
    const parent = node.parentNode;
    if (!parent)
      continue;
    const span = activeDocument.createElement("span");
    span.className = className;
    parent.insertBefore(span, node);
    span.appendChild(node);
    spans.push(span);
  }
  return spans;
}
function unwrapFlashSpans() {
  for (const span of activeFlashSpans) {
    const parent = span.parentNode;
    if (!parent)
      continue;
    while (span.firstChild)
      parent.insertBefore(span.firstChild, span);
    parent.removeChild(span);
    if (parent.nodeType === Node.ELEMENT_NODE) {
      parent.normalize();
    }
  }
  activeFlashSpans = [];
}
function anchorInSegment(n, part, seg) {
  if (n < seg.start || n > seg.end)
    return false;
  if (n === seg.start && seg.startPart !== null) {
    if (part === null)
      return false;
    if (part.charCodeAt(0) < seg.startPart.charCodeAt(0))
      return false;
  }
  if (n === seg.end && seg.endPart !== null && part !== null) {
    if (part.charCodeAt(0) > seg.endPart.charCodeAt(0))
      return false;
  }
  return true;
}
function collectInSegmentsAnchors(segments, root) {
  var _a;
  const all = root.querySelectorAll('[id^="verse-"]');
  const inRange = [];
  for (let i = 0; i < all.length; i++) {
    const el = all[i];
    const m = /^verse-(\d+)([a-z]+)?$/.exec(el.id);
    if (!m)
      continue;
    const n = parseInt(m[1], 10);
    const part = (_a = m[2]) != null ? _a : null;
    if (segments.some((seg) => anchorInSegment(n, part, seg)))
      inRange.push(el);
  }
  return inRange;
}
var FLASH_STOP_FOOTNOTE_SELECTORS = [
  "section.footnotes",
  ".footnotes",
  "ol.footnote-list"
];
var FLASH_STOP_HEADING_SELECTORS = ["h1", "h2", "h3", "h4", "h5", "h6"];
function findFlashStopBetween(a, b, includeHeadings, root) {
  const selectors = includeHeadings ? [...FLASH_STOP_FOOTNOTE_SELECTORS, ...FLASH_STOP_HEADING_SELECTORS] : FLASH_STOP_FOOTNOTE_SELECTORS;
  const candidates = root.querySelectorAll(selectors.join(","));
  for (let i = 0; i < candidates.length; i++) {
    const el = candidates[i];
    if (!(a.compareDocumentPosition(el) & Node.DOCUMENT_POSITION_FOLLOWING)) {
      continue;
    }
    if (b && !(el.compareDocumentPosition(b) & Node.DOCUMENT_POSITION_FOLLOWING)) {
      continue;
    }
    return el;
  }
  return null;
}
function buildVerseFlashRanges(segments, root) {
  var _a;
  const inRange = collectInSegmentsAnchors(segments, root);
  if (inRange.length === 0)
    return [];
  const allValidAnchors = [];
  const all = root.querySelectorAll('[id^="verse-"]');
  for (let i = 0; i < all.length; i++) {
    if (/^verse-\d+[a-z]*$/.test(all[i].id))
      allValidAnchors.push(all[i]);
  }
  const inRangeSet = new Set(inRange);
  const ranges = [];
  for (const anchor of inRange) {
    const idx = allValidAnchors.indexOf(anchor);
    const next = idx >= 0 ? allValidAnchors[idx + 1] : void 0;
    const prev = idx > 0 ? allValidAnchors[idx - 1] : void 0;
    const nextInSelection = next !== void 0 && inRangeSet.has(next);
    const prevInSelection = prev !== void 0 && inRangeSet.has(prev);
    const includeHeadings = !nextInSelection;
    const range = activeDocument.createRange();
    try {
      range.setStartBefore(anchor);
      const stop = findFlashStopBetween(
        anchor,
        next != null ? next : null,
        includeHeadings,
        root
      );
      if (stop) {
        range.setEndBefore(stop);
      } else if (next) {
        range.setEndBefore(next);
      } else {
        const last = root instanceof Element ? (_a = root.lastElementChild) != null ? _a : root.lastChild : root.lastChild;
        if (!last)
          continue;
        range.setEndAfter(last);
      }
      ranges.push({
        range,
        capStart: !prevInSelection,
        capEnd: !nextInSelection
      });
    } catch (e) {
      continue;
    }
  }
  return ranges;
}

// src/embeds.ts
var import_obsidian4 = require("obsidian");
function wrapAsDocumentBlocks(preview) {
  const doc = preview.ownerDocument;
  for (const child of Array.from(preview.children)) {
    const wrapper = doc.createElement("div");
    wrapper.className = `el-${child.tagName.toLowerCase()}`;
    preview.insertBefore(wrapper, child);
    wrapper.appendChild(child);
  }
}
var VerseEmbed = class extends import_obsidian4.Component {
  constructor(plugin, ctx, file, fragment) {
    super();
    this.plugin = plugin;
    this.ctx = ctx;
    this.file = file;
    this.fragment = fragment;
    this.renderToken = 0;
  }
  onload() {
    void this.render();
  }
  /** Obsidian calls this to (re)render when the source file changes. */
  async loadFile() {
    await this.render();
  }
  async render() {
    const myToken = ++this.renderToken;
    const allowShorthand = this.plugin.settings.enableShorthandSyntax;
    const segments = parseVerseSegments(this.fragment, allowShorthand);
    let markdown = null;
    if (segments) {
      markdown = await buildSegmentsPreviewMarkdown(
        this.plugin.app,
        this.file,
        segments,
        this.plugin.settings.hoverPreviewMaxVerses
      );
    }
    if (myToken !== this.renderToken)
      return;
    const container = this.ctx.containerEl;
    container.empty();
    container.removeClass("verse-embed-empty");
    container.addClasses(["markdown-embed", "is-loaded", "verse-embed"]);
    container.createDiv({
      cls: "embed-title markdown-embed-title",
      text: this.file.basename
    });
    if (!markdown) {
      container.addClass("verse-embed-empty");
      container.createDiv({
        cls: "markdown-embed-content",
        text: `Couldn't find "${this.fragment}"`
      });
      return;
    }
    const content = container.createDiv({ cls: "markdown-embed-content" });
    const preview = content.createDiv({
      cls: "markdown-rendered verse-embed-preview"
    });
    await import_obsidian4.MarkdownRenderer.render(
      this.plugin.app,
      convertHighlightSyntaxToHtml(markdown),
      preview,
      this.file.path,
      this
    );
    if (myToken !== this.renderToken)
      return;
    styleVerseMarkers(preview);
    wrapAsDocumentBlocks(preview);
    const link = container.createEl("a", {
      cls: "markdown-embed-link",
      attr: { "aria-label": "Open link" }
    });
    (0, import_obsidian4.setIcon)(link, "lucide-maximize-2");
    link.addEventListener("click", (ev) => {
      ev.preventDefault();
      ev.stopPropagation();
      void resolveVerseLink(
        this.plugin.app,
        this.file,
        this.fragment,
        allowShorthand
      );
    });
  }
};
function registerVerseEmbeds(plugin) {
  try {
    const registry = plugin.app.embedRegistry;
    if (!registry || typeof registry.embedByExtension !== "object")
      return;
    const original = registry.embedByExtension["md"];
    if (typeof original !== "function")
      return;
    const creator = (ctx, file, subpath) => {
      const fragment = (subpath != null ? subpath : "").replace(/^#/, "");
      if (fragment) {
        const segments = parseVerseSegments(
          fragment,
          plugin.settings.enableShorthandSyntax
        );
        if (segments)
          return new VerseEmbed(plugin, ctx, file, fragment);
      }
      return original(ctx, file, subpath);
    };
    registry.embedByExtension["md"] = creator;
    plugin.register(() => {
      registry.embedByExtension["md"] = original;
    });
  } catch (e) {
  }
}

// src/livePreview.ts
var import_view3 = require("@codemirror/view");
var import_state2 = require("@codemirror/state");
var VerseMarkerWidget = class extends import_view3.WidgetType {
  constructor(label, flashClass) {
    super();
    this.label = label;
    this.flashClass = flashClass;
  }
  eq(other) {
    return other instanceof VerseMarkerWidget && other.label === this.label && other.flashClass === this.flashClass;
  }
  /** Pass clicks/edits through; footnote `[^1]` after the widget stays interactive. */
  ignoreEvent() {
    return true;
  }
  toDOM() {
    const wrap = document.createElement("span");
    wrap.className = ["verse-marker-widget", this.flashClass].filter(Boolean).join(" ");
    const open = document.createElement("span");
    open.className = "verse-marker-bracket";
    open.textContent = "[";
    const label = document.createElement("span");
    label.className = "verse-marker";
    label.textContent = this.label;
    const close = document.createElement("span");
    close.className = "verse-marker-bracket";
    close.textContent = "]";
    wrap.append(open, label, close);
    return wrap;
  }
};
function markerInsideHighlight(from, to, highlights) {
  return highlights.some((h) => from >= h.start && to <= h.end);
}
function verseMarkerLabel2(token) {
  const { number, part } = parseMarkerToken(token);
  return `${number}${part != null ? part : ""}`;
}
function pushBracketLabelMarks(specs, tokenFrom, tokenTo) {
  specs.push(
    {
      from: tokenFrom,
      to: tokenFrom + 1,
      decoration: import_view3.Decoration.mark({ class: "verse-marker-bracket" }),
      atomic: false
    },
    {
      from: tokenFrom + 1,
      to: tokenTo - 1,
      decoration: import_view3.Decoration.mark({ class: "verse-marker" }),
      atomic: false
    },
    {
      from: tokenTo - 1,
      to: tokenTo,
      decoration: import_view3.Decoration.mark({ class: "verse-marker-bracket" }),
      atomic: false
    }
  );
}
function collectDecorationSpecs(view) {
  const doc = view.state.doc;
  const fullText = doc.toString();
  const highlights = findHighlightRanges(fullText);
  const specs = [];
  for (const { from, to } of view.visibleRanges) {
    let pos = from;
    while (pos < to) {
      const slice = doc.sliceString(pos, to);
      const brRel = findVerseBreakIndex(slice);
      const markerRe = getVerseRegex();
      const m = execVerseMarker(markerRe, slice);
      const brIdx = brRel === -1 ? -1 : pos + brRel;
      const markerIdx = m ? pos + m.index : -1;
      if (brIdx === -1 && markerIdx === -1)
        break;
      if (markerIdx === -1 || brIdx !== -1 && brIdx < markerIdx) {
        const breakFrom = brIdx;
        const breakTo = brIdx + VERSE_BREAK_TOKEN.length;
        if (markerInsideHighlight(breakFrom, breakTo, highlights)) {
          specs.push({
            from: breakFrom + 1,
            to: breakTo - 1,
            decoration: import_view3.Decoration.mark({ class: "verse-marker" }),
            atomic: false
          });
        } else {
          pushBracketLabelMarks(specs, breakFrom, breakTo);
        }
        pos = breakTo;
        continue;
      }
      const matchFrom = markerIdx;
      const matchTo = markerIdx + m[0].length;
      const beforeFootnote = isFollowedByFootnoteRef(fullText, matchTo);
      if (beforeFootnote) {
        specs.push({
          from: matchFrom,
          to: matchTo,
          decoration: import_view3.Decoration.replace({
            widget: new VerseMarkerWidget(
              verseMarkerLabel2(m[0]),
              flashClassesForWidget(matchFrom, matchTo)
            ),
            inclusive: false,
            block: false
          }),
          atomic: true
        });
      } else {
        pushBracketLabelMarks(specs, matchFrom, matchTo);
      }
      pos = matchTo;
    }
  }
  specs.sort((a, b) => a.from - b.from);
  return specs;
}
function buildDecorations(view) {
  const specs = collectDecorationSpecs(view);
  const allBuilder = new import_state2.RangeSetBuilder();
  const atomicBuilder = new import_state2.RangeSetBuilder();
  for (const { from, to, decoration, atomic } of specs) {
    allBuilder.add(from, to, decoration);
    if (atomic)
      atomicBuilder.add(from, to, decoration);
  }
  return {
    all: allBuilder.finish(),
    atomic: atomicBuilder.finish()
  };
}
function transactionHasFlashChange(tr) {
  for (const e of tr.effects) {
    if (e.is(setVerseFlashEffect))
      return true;
  }
  return false;
}
var VerseMarkerLivePreviewPlugin = class {
  constructor(view) {
    const built = buildDecorations(view);
    this.decorations = built.all;
    this.atomicDeco = built.atomic;
  }
  update(update) {
    const flashChanged = update.transactions.some(transactionHasFlashChange);
    if (update.docChanged || update.viewportChanged || flashChanged) {
      const built = buildDecorations(update.view);
      this.decorations = built.all;
      this.atomicDeco = built.atomic;
    }
  }
};
function verseMarkerLivePreviewExtension() {
  let plugin;
  plugin = import_view3.ViewPlugin.fromClass(VerseMarkerLivePreviewPlugin, {
    decorations: (p) => p.decorations,
    provide: () => import_view3.EditorView.atomicRanges.of(
      (view) => {
        var _a, _b;
        return (_b = (_a = view.plugin(plugin)) == null ? void 0 : _a.atomicDeco) != null ? _b : import_view3.Decoration.none;
      }
    )
  });
  return plugin;
}

// src/settings.ts
var import_obsidian5 = require("obsidian");
var DEFAULT_SETTINGS = {
  enableHoverPreviews: true,
  hoverPreviewMaxVerses: 20,
  enableShorthandSyntax: false,
  keepHighlightUntilClick: false
};
var VerseMarkersSettingTab = class extends import_obsidian5.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian5.Setting(containerEl).setName("Reference syntax").setHeading();
    const syntaxEl = containerEl.createEl("div", {
      cls: "setting-item-description verse-markers-syntax-ref"
    });
    syntaxEl.createEl("strong", { text: "Reference syntax:" });
    syntaxEl.createEl("br");
    syntaxEl.appendText(
      "Default \u2014 [[File#verse-3]], [[File#verse-3a]] / [[File#verse-3b]] (heading-split parts), [[File#verse-3:7]] (range)"
    );
    syntaxEl.createEl("br");
    syntaxEl.appendText(
      "Shorthand (opt-in below) \u2014 [[File#3]] / [[File#3a]] / [[File#3:7]]"
    );
    new import_obsidian5.Setting(containerEl).setName("Enable range hover previews").setDesc("Show a popover with verse content when hovering over [[FILE#verse-N:M]] links.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enableHoverPreviews).onChange(async (value) => {
        this.plugin.settings.enableHoverPreviews = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian5.Setting(containerEl).setName("Enable shorthand reference syntax").setDesc(
      'Recognize [[File#3]] and [[File#3:7]] in addition to the default [[File#verse-3]] form. Warning: enabling this will intercept links to headings literally named "3" or "3:7".'
    ).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enableShorthandSyntax).onChange(async (value) => {
        this.plugin.settings.enableShorthandSyntax = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian5.Setting(containerEl).setName("Navigation highlight").setHeading();
    new import_obsidian5.Setting(containerEl).setName("Keep temporary highlight until click").setDesc(
      "When off (default), the verse highlight after navigation fades automatically after a few seconds. When on, it stays visible until you click elsewhere."
    ).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.keepHighlightUntilClick).onChange(async (value) => {
        this.plugin.settings.keepHighlightUntilClick = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian5.Setting(containerEl).setName("Max verses in hover preview").setDesc("Maximum number of verses to display in a range hover preview.").addText(
      (text) => text.setPlaceholder("20").setValue(String(this.plugin.settings.hoverPreviewMaxVerses)).onChange(async (value) => {
        const num = parseInt(value, 10);
        if (!isNaN(num) && num > 0) {
          this.plugin.settings.hoverPreviewMaxVerses = num;
          await this.plugin.saveSettings();
        }
      })
    );
  }
};

// src/main.ts
var VerseMarkersPlugin = class extends import_obsidian6.Plugin {
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new VerseMarkersSettingTab(this.app, this));
    this.registerEditorExtension([
      verseMarkerLivePreviewExtension(),
      verseFlashExtension()
    ]);
    this.registerMarkdownPostProcessor((el, ctx) => {
      versePostProcessor(el, ctx);
    });
    registerVersePagePreview(this);
    registerVerseLinkNavigation(this);
    configureVerseHighlightBehavior(() => this.settings);
    registerVerseHighlightDismiss(this);
    onVerseHighlightDismiss(() => clearReadingViewHighlight());
    onVerseHighlightDismiss(() => clearActiveLivePreviewFlash());
    registerNativeFlashPrevention(this);
    registerVerseEmbeds(this);
    registerCommands(this);
    this.registerObsidianProtocolHandler("verse-markers", async (params) => {
      const verse = params["verse"];
      const filePath = params["file"];
      if (!verse || !filePath)
        return;
      const file = this.app.vault.getAbstractFileByPath(filePath);
      if (!(file instanceof import_obsidian6.TFile))
        return;
      const vm = /^(\d+)([a-z]*)$/.exec(verse);
      if (!vm)
        return;
      const verseNum = parseInt(vm[1], 10);
      const part = vm[2] || params["part"] || "";
      const fragment = part ? `verse-${verseNum}${part}` : `verse-${verseNum}`;
      await resolveVerseLink(this.app, file, fragment);
    });
  }
  async loadSettings() {
    const data = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, data != null ? data : {});
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
